import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "hu" | "en" | "zh";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "hu",
  setLang: () => {},
  t: (key) => key,
});

// ─── Translations ────────────────────────────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  hu: {
    // Navigation
    "nav.services": "Szolgáltatások",
    "nav.expertise": "Szakértelem",
    "nav.technology": "Technológia",
    "nav.partners": "Partnereink",
    "nav.blog": "Blog",
    "nav.about": "Rólunk",
    "nav.references": "Referenciák",
    "nav.contact": "Kapcsolat",
    "nav.freeAudit": "Ingyenes Audit",
    "nav.industries": "Iparágak",
    "nav.newsletter": "Hírlevél",
    "nav.career": "Karrier",

    // Services
    "service.localization": "Lokalizáció",
    "service.branding": "Arculattervezés",
    "service.ads": "Hirdetéskezelés",
    "service.social": "Közösségi Média",
    "service.strategy": "Stratégiai Marketing",
    "service.seo": "Keresőoptimalizálás",
    "service.webdev": "Webfejlesztés",
    "service.aiMarketing": "AI Marketing",
    "service.ppc": "PPC / Google Ads",
    "service.meta": "Meta Hirdetések",
    "service.content": "Tartalommarketing",
    "service.automation": "Marketing Automatizáció",
    "service.esg": "ESG Kommunikáció",
    "service.employerBranding": "Employer Branding",
    "service.international": "Nemzetközi Marketing",

    // Industries
    "industry.healthcare": "Egészségügy",
    "industry.beauty": "Szépségipar",
    "industry.engineering": "Mérnöki irodák",
    "industry.automotive": "Autóipar",
    "industry.legal": "Ügyvédi irodák",
    "industry.technology": "Technológia",
    "industry.government": "Önkormányzat",
    "industry.b2b": "B2B vállalatok",

    // Hero
    "hero.badge": "Adatvezérelt Marketing Ügynökség",
    "hero.title1": "Növeljük vállalkozásod",
    "hero.title2": "digitális jelenlétét",
    "hero.subtitle": "Stratégiai marketing megoldások, amelyek valódi eredményeket hoznak. SEO, hirdetések, közösségi média és webfejlesztés – egy helyen.",
    "hero.cta1": "Ingyenes konzultáció",
    "hero.cta2": "Referenciáink",

    // Common
    "common.readMore": "Tovább olvasom",
    "common.contactUs": "Kapcsolatfelvétel",
    "common.freeAudit": "Ingyenes Audit kérése",
    "common.learnMore": "Tudj meg többet",
    "common.allServices": "Összes szolgáltatás",
    "common.back": "Vissza",
    "common.send": "Küldés",
    "common.name": "Név",
    "common.email": "E-mail",
    "common.phone": "Telefon",
    "common.message": "Üzenet",
    "common.company": "Cég neve",
    "common.website": "Weboldal",
    "common.loading": "Betöltés...",
    "common.success": "Sikeresen elküldve!",
    "common.error": "Hiba történt. Kérjük próbálja újra.",
    "common.close": "Bezárás",
    "search.title": "Keresés",
    "search.placeholder": "Keresés cikkek és esettanulmányok között...",
    "search.minChars": "Írj legalább 2 karaktert a kereséshez.",
    "search.noResults": "Nincs találat erre: \"{q}\"",
    "search.navigate": "navigálás",
    "search.open": "megnyitás",
    "search.close": "bezárás",
    "search.openShortcut": "Keresés (Ctrl+K)",
    "cookie.message": "Ez az oldal sütiket csak akkor használ, ha kifejezetten kéred (pl. időpontfoglalás Calendly-vel). Az alapszintű látogatottságot cookie-mentes Plausible-lel mérjük.",
    "cookie.link": "Adatvédelmi irányelvek",
    "cookie.accept": "Elfogadom",
    "cookie.decline": "Elutasítom",
    "cookie.close": "Bezárás",
    "cookie.title": "Süti hozzájárulás",
    "cookie.acceptAll": "Az összes elfogadása",
    "cookie.rejectAll": "Csak a szükségeseket",
    "cookie.customize": "Beállítások testreszabása",
    "cookie.savePreferences": "Beállítások mentése",
    "cookie.alwaysOn": "Mindig aktív",
    "cookie.cat.necessary": "Szükséges",
    "cookie.cat.necessary.desc": "Az oldal alapvető működéséhez (admin login, téma, hozzájárulás emlékezete). Nem kapcsolható ki.",
    "cookie.cat.functional": "Funkcionális",
    "cookie.cat.functional.desc": "A felhasználói élményt javító, de nem nélkülözhetetlen funkciók (nyelvi beállítások emlékezete, megjelenés-finomhangolások).",
    "cookie.cat.thirdParty": "Beágyazott szolgáltatások",
    "cookie.cat.thirdParty.desc": "Az időpontfoglaló (Calendly) widget. Hozzájárulás nélkül nem töltődik be — alternatívaként közvetlenül e-mailben elérhetsz minket.",
    "cookie.cat.marketing": "Marketing",
    "cookie.cat.marketing.desc": "Hirdetési, célzási és statisztikai sütik. Jelenleg nem használunk ilyet, de a beállítást előre tudod jelezni.",
    "common.required": "Kötelező mező",

    // Newsletter (shared across <NewsletterForm/>, footer band, popup, /hirlevel)
    "newsletter.emailLabel": "E-mail cím",
    "newsletter.emailPlaceholder": "te@cegeden.hu",
    "newsletter.nameLabel": "Keresztnév",
    "newsletter.namePlaceholder": "Pl. Anna",
    "newsletter.namePlaceholderRequired": "Keresztnév",
    "newsletter.topics.legend": "Mely témák érdekelnek?",
    "newsletter.topics.help": "Csak a kiválasztott témákról kapsz hírlevelet. Legalább 1-et kell választanod — később bármikor módosíthatod a profilodon.",
    "newsletter.topics.selectAll": "Az összes kijelölése",
    "newsletter.topics.deselectAll": "Az összes törlése",
    "newsletter.topics.strategy.label": "B2B marketing stratégia",
    "newsletter.topics.strategy.desc": "Pozícionálás, ICP, brand-építés, GTM",
    "newsletter.topics.ai.label": "AI & automatizáció",
    "newsletter.topics.ai.desc": "AI eszközök, prompt-receptek, workflow tippek",
    "newsletter.topics.paid.label": "SEO & teljesítményhirdetés",
    "newsletter.topics.paid.desc": "Google Ads, Meta hirdetések, organikus SEO",
    "newsletter.topics.case_studies.label": "Esettanulmányok & adatok",
    "newsletter.topics.case_studies.desc": "Anonim ügyfélprojektek, valós számok",
    "newsletter.submit": "Feliratkozom",
    "newsletter.submitting": "Feliratkozás...",
    "newsletter.success": "Sikeres feliratkozás! Hamarosan kapsz egy üdvözlő emailt.",
    "newsletter.error": "Hiba történt a feliratkozás során. Próbáld újra később!",
    "newsletter.consent.before": "Hozzájárulok, hogy a G2A Marketing Bt. e-mailen marketing tartalmakat küldjön. Részleteket találsz az",
    "newsletter.consent.linkText": "adatvédelmi tájékoztatóban",
    "newsletter.consent.after": "; bármikor leiratkozhatok egy kattintással.",
    "newsletter.benefits.0": "Heti 1 email — sose több",
    "newsletter.benefits.1": "Konkrét B2B taktikák, AI-eszközök, esettanulmányok",
    "newsletter.benefits.2": "Egyetlen kattintás a leiratkozás",
    "newsletter.benefits.3": "Adataidat sose adjuk át harmadik félnek",
    "newsletter.bandLabel": "Hírlevél",
    "newsletter.bandTitle": "Heti egy email a B2B marketingről",
    "newsletter.bandSubtitle": "Pénteken reggel 1 stratégiai gondolat + 1 konkrét taktika + 1 használható eszköz. Spam-mentes.",
    "newsletter.bandFinePrint": "A feliratkozással elfogadod az Adatvédelmi tájékoztatót. Egy kattintással leiratkozhatsz.",
    "newsletter.popup.title": "Maradj naprakész",
    "newsletter.popup.subtitle": "Heti 1 email a B2B marketing trendekről, AI-eszközökről és gyakorlati tippekről. Spam-mentes — egy kattintással leiratkozhatsz.",
    "newsletter.popup.dismiss": "Most nem",

    // Footer
    "footer.rights": "Minden jog fenntartva.",
    "footer.privacy": "Adatvédelmi irányelvek",
    "footer.terms": "ÁSZF",
    "footer.cookieSettings": "Cookie beállítások",
    "footer.impressum": "Impresszum",
    "footer.impressum.address": "Székhely",
    "footer.impressum.regNumber": "Cégjegyzékszám",
    "footer.impressum.taxNumber": "Adószám",
    "footer.orBookSlot": "vagy",
    "footer.bookSlotLink": "foglalj 30 perces időpontot",
    "footer.services": "Szolgáltatások",
    "footer.company": "Cég",
    "footer.contact": "Kapcsolat",
    "footer.workingHours": "Munkaidő",
    "footer.workingHoursValue": "H–P: 08:00–17:00",

    // Contact
    "contact.title": "Kapcsolat — lépjünk kapcsolatba",
    "contact.subtitle": "Szívesen beszélünk az ötleteidről és kihívásaidról: új weboldal-projekt, hirdetésstratégia, AI-integráció vagy bármilyen marketing kérdés. Töltsd ki az alábbi űrlapot, írj e-mailt vagy foglalj 30 perces ingyenes konzultációt — 1–2 munkanapon belül válaszolunk.",
    "contact.formTitle": "Írj nekünk",
    "contact.subject": "Tárgy",
    "contact.send": "Üzenet küldése",

    // Blog
    "blog.title": "Marketing Hírek & Tippek",
    "blog.subtitle": "Naprakész tartalmak a digitális marketing világából.",
    "blog.readMore": "Tovább olvasom",
    "blog.allCategories": "Összes kategória",
    "blog.latestPosts": "Legújabb cikkek",

    // About
    "about.title": "Rólunk",
    "about.subtitle": "Adatvezérelt marketing ügynökség, amely valódi eredményeket hoz.",

    // References
    "references.title": "Referenciák & Esettanulmányok",
    "references.subtitle": "Valós eredmények, valós ügyfelektől.",
    "references.challenge": "Kihívás",
    "references.solution": "Megoldás",
    "references.results": "Eredmények",
    "references.all": "Összes",

    // Audit
    "audit.title": "Ingyenes Marketing Audit",
    "audit.subtitle": "Derítsd ki, mi tartja vissza vállalkozásod növekedését.",
    "audit.cta": "Audit kérése",
    "audit.currentChallenges": "Jelenlegi kihívások",
    "audit.currentBudget": "Jelenlegi marketing büdzsé",
    "audit.website": "Weboldal URL",

    // Cookie
    // Expertise page
    "expertise.sectionLabel": "Szakterületek",
    "expertise.title": "Iparágak, ahol otthon vagyunk",
    "expertise.desc": "Tapasztalatunk számos szektorra kiterjed. Pontosan értjük az adott piac kihívásait és lehetőségeit.",
    // Partners page
    "partners.sectionLabel": "Referenciák",
    "partners.title": "Partnereink és referenciáink",
    "partners.desc": "Büszkék vagyunk arra, hogy számos sikeres vállalkozás bízta ránk digitális marketing feladatait.",
    "partners.visitWebsite": "Weboldal megtekintése",
    // Technology page
    "technology.sectionLabel": "Eszközök",
    "technology.title": "Technológiák, amelyeket használunk",
    "technology.desc": "A legmodernebb marketing és AI eszközöket alkalmazzuk, hogy ügyfeleink mindig a legjobb eredményeket kapják.",
    // Services page
    "services.sectionLabel": "Amit kínálunk",
    "services.title": "Teljes körű digitális marketing megoldások",
    "services.desc": "Minden, amire vállalkozásodnak szüksége van a digitális sikerhez – egy helyen.",
    // About page extra
    "about.sectionLabel": "Rólunk",
    "about.tagline": "Stratégiai partnerek a növekedésedben",
    "about.desc": "2022 óta segítünk B2B cégeknek mérhető marketing eredményeket elérni.",
    "about.founded": "Alapítva",
    "about.team": "Csapatunk",
    "about.values": "Értékeink",
    "about.milestones": "Mérföldkövek",
    // References page extra
    "references.sectionLabel": "Esettanulmányok",
    "references.viewDetails": "Részletek megtekintése",
    "references.filterAll": "Összes iparág",
    "references.readMore": "Teljes esettanulmány",
    "references.back": "Vissza a referenciákhoz",
    // Blog page extra
    "blog.sectionLabel": "Blog",
    "blog.allPosts": "Összes",
    "blog.noResults": "Nem találhatók cikkek ebben a kategóriában.",
    "blog.emptyTitle": "Még nincsenek cikkek",
    "blog.emptyDesc": "Hamarosan friss tartalmakkal jelentkezünk a marketing világából.",
    "blog.emptyCategoryTitle": "Nincs cikk ebben a kategóriában",
    "blog.emptyCategoryDesc": "Próbálj egy másik kategóriát, vagy nézd meg az összes cikket.",
    "blog.viewAllPosts": "Összes cikk",
    "blog.read": "Olvasás",
    // Audit page extra
    "audit.sectionLabel": "Ingyenes ajánlat",
    "audit.submit": "Audit kérése – Teljesen Ingyenes",
    "audit.submitting": "Küldés folyamatban...",
    // SEO Audit page
    "seoAudit.title": "Ingyenes SEO Audit",
    "seoAudit.subtitle": "Derítsd ki, mi akadályozza Google rangsorolásodat",
    "seoAudit.placeholder": "https://cegedneve.hu",
    "seoAudit.cta": "Ingyenes SEO Audit kérése",
    // Popup
    "popup.title": "Mielőtt elmész...",
    "popup.desc": "Kérd az ingyenes marketing auditot és derítsd ki, hogyan növelheted bevételeidet 30%-kal!",
    "popup.cta": "Igen, kérem az ingyenes auditot!",
    "popup.decline": "Nem, köszönöm",
    // Sticky CTA
    "stickyCta.text": "Ingyenes Audit",
    // Nav extras
    "nav.home": "Főoldal",
    "nav.viewAllServices": "Összes szolgáltatás megtekintése",
    "nav.freeAuditFull": "Ingyenes Marketing Audit",
    // Service descriptions (nav dropdown)
    "service.localization.desc": "Többnyelvű marketing",
    "service.branding.desc": "Brand identitás",
    "service.ads.desc": "PPC & Meta Ads",
    "service.social.desc": "Social media menedzsment",
    "service.strategy.desc": "Teljes marketing stratégia",
    "service.seo.desc": "SEO & tartalommarketing",
    "service.webdev.desc": "Modern weboldalak",
    "service.aiMarketing.desc": "AI-alapú megoldások",
    "service.automation.desc": "Workflow automatizálás",
    "service.esg.desc": "Fenntarthatósági marketing",
    "service.employerBranding.desc": "Munkáltatói márkaépítés",
    "service.international.desc": "Globális jelenlét",
    // Industries (extras)
    // Contact page
    "contact.directContact": "Közvetlen elérhetőségek",
    "contact.address": "Cím",
    "contact.addressValue": "Pécs, Magyarország",
    "contact.formName": "Neved",
    "contact.formEmail": "Email címed",
    "contact.formPhone": "Telefonszámod (opcionális)",
    "contact.formCompany": "Cég neve (opcionális)",
    "contact.formSubject": "Tárgy",
    "contact.formMessage": "Üzenet",
    "contact.sending": "Küldés...",
    "contact.successTitle": "Üzenet elküldve!",
    "contact.successDesc": "Köszönjük megkeresésed! Hamarosan felvesszük veled a kapcsolatot.",
    "contact.errorMsg": "Hiba történt az üzenet küldésekor. Kérjük próbáld újra.",
    "contact.wechatTitle": "Kínai piaci partnereinknek",
    "contact.wechatDesc": "Ügyvezetőnk, Győrfi Attila a Varsói Egyetem vendégoktatójaként és nemzetközi marketing szakértőként rendszeresen dolgozik kínai piaci projekteken. Ha kínai piaci belépési vagy lokalizációs tanácsadásra van szükséged, WeChat-en gyors válaszadásra is elérhető — olvasd be a QR kódot.",
    "contact.wechatScan": "Olvasd be a QR kódot",
    "contact.contactInfo": "Elérhetőségeink",
    "contact.formHint24h": "Töltsd ki az alábbi űrlapot és 24 órán belül visszajelzünk.",
    "contact.sendAnother": "Új üzenet küldése",
    "contact.subjectPlaceholder": "Miben segíthetünk?",
    "contact.messagePlaceholder": "Írd le részletesen, miben segíthetünk...",
    "contact.location": "Helyszín",
    "contact.messageSentToast": "Üzeneted megkaptuk! Hamarosan felvesszük veled a kapcsolatot.",
    "contact.errorMessageMin": "Az üzenet legalább 10 karakter legyen.",
    "contact.calendlyTitle": "Vagy foglalj rögtön időpontot",
    "contact.calendlyDesc": "30 perces ingyenes konzultáció — kötelezettség nélkül, az időpontot te választod.",
    "contact.calendlyHintAfterAudit": "💡 Vagy foglalj rögtön egy ingyenes 30 perces konzultációt:",
    "contact.seoTitle": "Kapcsolat – G2A Marketing Pécs",
    "contact.seoDesc": "Vedd fel velünk a kapcsolatot! Telefon: +36301902575, Email: info@g2amarketing.hu",
    // Services page
    "services.seoTitle": "Szolgáltatások – G2A Marketing Pécs",
    "services.details": "Részletek",
    "services.freeConsultationCta": "Kérj ingyenes konzultációt!",
    // Technology page
    "technology.seoTitle": "Technológia – G2A Marketing Pécs",
    // Date locale tag
    "common.dateLocale": "hu-HU",
    // Home page
    "home.hero.badge": "Stratégiai partnerség KKV-knak és B2B cégeknek",
    "home.hero.title1": "Stratégiai marketing,",
    "home.hero.title2": "mérhető növekedés",
    "home.hero.subtitle": "Üzleti problémákra adunk megoldást. A G2A Marketing olyan stratégiai és technológiai partner, amely adatvezérelt marketingrendszert épít vállalkozásodnak — a kutatástól a megvalósításig. Tapasztalt szakértőink összekapcsolják a kreativitást, az analitikát és a mesterséges intelligenciát, hogy fenntartható növekedést érj el.",
    "home.stats.projects": "Sikeres projekt",
    "home.stats.industries": "Iparág",
    "home.stats.countries": "Ország",
    "home.stats.clients": "Elégedett ügyfél",
    "home.stats.partners": "Aktív partner",
    "home.stats.foundedSince": "Alapítás éve",
    "home.targetAudience.label": "Célcsoportjaink",
    "home.targetAudience.title": "Kinek segítünk?",
    "home.targetAudience.desc": "KKV-któl nagyvállalatig, egészségügytől autóiparig – 8+ iparágban bizonyított tapasztalattal",
    "home.solutions.label": "Megoldások",
    "home.solutions.title": "Mi a te problémád?",
    "home.solutions.desc": "Nem hagyományos kategóriák szerint gondolkodunk – a te üzleti kihívásaidból indulunk ki",
    "home.allReferences": "Összes referencia",
    "home.cases.label": "Referenciák",
    "home.cases.title": "Valós eredmények, valós ügyfelektől",
    "home.cases.subtitle": "Nem ígérünk – bizonyítunk. Íme néhány partnerünk projektje.",
    // Home — hero scroll hint + problems CTA
    "home.hero.scrollHint": "Görgess",
    "home.solutions.viewSolution": "Megoldás megtekintése",
    // Home — AI section
    "home.ai.label": "AI & Innováció",
    "home.ai.title": "Hogyan használjuk az AI-t?",
    "home.ai.desc": "Az AI nem a jövő – a mi napi eszközünk. Minden folyamatunkba integrálva van, hogy gyorsabban és hatékonyabban dolgozzunk az ügyfelekért.",
    "home.ai.cta": "AI Marketing megoldások",
    // Home — Why Us section
    "home.whyUs.label": "Miért G2A?",
    "home.whyUs.title": "Miért válassz minket?",
    "home.whyUs.desc": "Nem csak egy ügynökség vagyunk – stratégiai partnerek vagyunk a növekedésedben",
    // Home — Newsletter
    "home.newsletter.emailPlaceholder": "Email cím",
    "home.newsletter.success": "Sikeresen feliratkoztál!",
    // Home — Audit form
    "home.audit.thanks": "Köszönjük!",
    "home.audit.thanksDesc": "24 órán belül felvesszük veled a kapcsolatot.",
    "home.audit.namePlaceholder": "Kovács János",
    "home.audit.companyLabel": "Cég neve",
    "home.audit.companyPlaceholder": "Cég Kft.",
    "home.audit.messageLabel": "Rövid leírás (opcionális)",
    "home.audit.messagePlaceholder": "Miben segíthetünk?",
    "home.audit.submit": "Audit kérése – Ingyenesen",
    "home.audit.submitting": "Küldés...",
    // Common — error
    "common.tryAgainError": "Hiba történt. Kérjük, próbáld újra.",
    // References page
    "references.heroTitle1": "Valós eredmények,",
    "references.heroTitle2": "valós ügyfelektől",
    "references.heroDesc": "Nem ígérünk – bizonyítunk. Íme néhány ügyfél esettanulmánya, ahol mérhető eredményeket értünk el.",
    "references.badge.partners": "23+ partner",
    "references.badge.industries": "8+ iparág",
    "references.badge.results": "Mérhető eredmények",
    "references.empty.allTitle": "Nincs publikált esettanulmány",
    "references.empty.allDesc": "Az új esettanulmányokon dolgozunk – addig is, beszéljünk a Te projektedről.",
    "references.empty.industryTitle": "Ebben az iparágban még nincs esettanulmány",
    "references.empty.industryDesc": "Próbálj egy másik iparágat, vagy nézd meg az összes esettanulmányt.",
    "references.empty.viewAll": "Összes esettanulmány",
    "references.statsLabel": "Számokban",
    "references.statsTitle": "Eredményeink összesítve",
    "references.stats.partners": "Aktív partner",
    "references.stats.industries": "Iparág",
    "references.stats.traffic": "Átlagos forgalom növekedés",
    "references.stats.roas": "Átlagos ROAS",
    "references.finalCta.title": "Te lehetsz a következő sikertörténet",
    "references.finalCta.desc": "Kérj ingyenes marketing auditot és megmutatjuk, hogyan érhetünk el hasonló eredményeket a te vállalkozásodban.",
    "references.contactCta": "Kapcsolatfelvétel",
    // Case study detail extras
    "cs.startYear": "Indulás éve",
    "cs.links": "Linkek",
    // Blog page
    "blog.notFoundDesc": "Lehet hogy elköltözött vagy nincs még publikálva. Térj vissza a cikklistához.",
    "blog.minRead": "perc olvasás",
    // Navigation extras
    "nav.openMenu": "Menü",
    "nav.logoAlt": "G2A Marketing logó",
    "nav.closeButton": "Bezárás",
    "common.loading2": "Töltés",
    "home.audit.desc": "Megvizsgáljuk a teljes online jelenlétedet és megmutatjuk, hol veszítesz el ügyfeleket – teljesen ingyenesen.",
    "home.audit.cta": "Kérd az ingyenes auditot",
    "home.audit.followup": "24 órán belül felvesszük veled a kapcsolatot.",
    "home.testimonials.label": "Vélemények",
    "home.testimonials.title": "Mit mondanak az ügyfeleink?",
    "home.faq.label": "GYIK",
    "home.faq.title": "Gyakori kérdések",
    "home.newsletter.label": "Hírlevél",
    "home.newsletter.title": "Marketing trendek, minden héten",
    "home.newsletter.desc": "Iratkozz fel hírlevelünkre és kapj heti marketing tippeket, esettanulmányokat és AI-újdonságokat.",
    "home.newsletter.submit": "Feliratkozás",
    "home.newsletter.submitting": "Feliratkozás...",
    "home.newsletter.morePrefs": "Több beállítás (témaválasztás)",
    "home.finalCta.title": "Készen állsz a növekedésre?",
    "home.finalCta.desc": "Vedd fel velünk a kapcsolatot és indítsuk el a közös munkát egy ingyenes konzultációval.",
    "common.projectsSuffix": "projekt",
    // About page (Rólunk)
    "about.seoTitle": "Rólunk – G2A Marketing | Adatvezérelt B2B Marketing Ügynökség",
    "about.seoDesc": "Ismerd meg a G2A Marketing csapatát. 2022 óta segítünk B2B cégeknek mérhető marketing eredményeket elérni. Stratégiai gondolkodás, AI-alapú megoldások, 23+ aktív partner.",
    "about.heroTitle1": "Stratégiai partnerek a",
    "about.heroTitle2": "növekedésedben",
    "about.heroDesc": "2022 óta segítünk B2B cégeknek mérhető marketing eredményeket elérni. Nem csak ügynökség vagyunk – stratégiai partnerek vagyunk a hosszú távú növekedésben.",
    "about.stats.founded": "Alapítás éve",
    "about.stats.partners": "Aktív partner",
    "about.stats.industries": "Iparág",
    "about.stats.years": "Aktív év",
    "about.stats.commitment": "Elkötelezettség",
    "about.story.label": "Történetünk",
    "about.story.title": "Hogyan kezdődött?",
    "about.story.p1": "A G2A Marketing 2022-ben alakult Pécsett azzal a céllal, hogy a magyar KKV-k és B2B vállalatok is elérhetővé tegyük az olyan adatvezérelt, stratégiai marketing-megközelítést, amelyik addig csak a nagyvállalatok privilégiuma volt. Az alapító Győrfi Attila a Pécsi Tudományegyetem Közgazdaságtudományi Karának egykori hallgatójaként, majd vendégoktatójaként közvetlenül látta a piaci szakadékot: a hazai cégek többsége vagy túl drágán dolgozott egy budapesti ügynökséggel, vagy egyáltalán nem foglalkozott marketinggel — közben a forgalom egyre inkább online ment.",
    "about.story.p2": "Az indulástól fókuszált specializáció jellemzett minket: az első 10 partnerünk az egészségügy és szépségipar területéről érkezett, ahol a regulációs és vizuális kihívások egyszerre vannak jelen. 2023-ban autóiparra és vendéglátásra terjedtünk ki (Honda, Nissan, Café Frei, Tüke Busz). 2024-ben az AI-eszközök operatív integrálása lett a stratégiánk magja — ma a Claude, ChatGPT, Manus és Midjourney napi munkaeszközünk. 2025-re 23+ aktív partnerünk van 8 iparágban — mind valós, mérhető eredménnyel.",
    "about.story.p3": "Nem akarunk a legnagyobb ügynökség lenni Magyarországon. Azt akarjuk, hogy a partnereink azt mondhassák: „velük dolgoztunk együtt — mi nőttünk, ők is.\” Ez a célunk, és ezt mérjük évente.",
    "about.story.cta": "Dolgozzunk együtt",
    "about.mission.label": "Misszió és vízió",
    "about.mission.title": "Amiért dolgozunk",
    "about.mission.missionTitle": "Misszió",
    "about.mission.missionBody": "Stratégiai és technológiai partnerként segítünk magyar KKV-knak és B2B vállalatoknak adatvezérelt marketingrendszert építeni — a kutatástól a megvalósításig. Hisszük, hogy a marketing nem költség, hanem mérhető megtérülésű befektetés, ha jól csináljuk.",
    "about.mission.visionTitle": "Vízió",
    "about.mission.visionBody": "Olyan ügynökség akarunk lenni, amelynél a magyar középvállalat szakembereinek 5 év múlva is megéri dolgozni — mert nálunk az AI nem helyettesíti, hanem felerősíti a szakmai döntést. 2030-ra Közép-Európa legautoritáltabb hangja akarunk lenni a B2B és KKV-marketing területén.",
    "about.whyUs.label": "Miért G2A?",
    "about.whyUs.title": "Mi különböztet meg minket?",
    "about.whyUs.point1Title": "Stratégia, nem kampány",
    "about.whyUs.point1Body": "Mielőtt egy kampányt elindítunk, audit + piackutatás + KPI-keret készül. Aki szerint a marketing „néhány szép poszt”, az nem velünk fog dolgozni.",
    "about.whyUs.point2Title": "Mérhető eredmények, nem ígéretek",
    "about.whyUs.point2Body": "Minden ügyfélnek dashboard készül HubSpot/GA4/Looker Studio alapokon. Az első hónapban azonosítjuk a baseline-t, utána havonta látható a növekedés — vagy a hiánya, és akkor változtatunk.",
    "about.whyUs.point3Title": "AI mélyen integrálva",
    "about.whyUs.point3Body": "Nem csak hirdetjük az AI-t — mi magunk használjuk Claude, ChatGPT, Manus, Midjourney, Runway, ElevenLabs eszközöket napi szinten. Ez a tapasztalat 30-50% gyorsabb tartalom-pipeline-t jelent ügyfeleinknek.",
    "about.whyUs.point4Title": "Hosszú távú partnerség",
    "about.whyUs.point4Body": "Átlagos ügyfélkapcsolatunk 18+ hónap. Nem akarunk gyors lefutó projekt-cégek lenni. Aki velünk indul, jellemzően 3 hónapos pilot után marad.",
    "about.whyUs.point5Title": "Pécsi gyökerek, nemzetközi szemlélet",
    "about.whyUs.point5Body": "Pécsi székhely, magyar és nemzetközi ügyfelek. Az ügyvezetőnk a Varsói Egyetem vendégoktatója — közvetlen lengyel, cseh, kínai piaci kapcsolatokkal.",
    "about.whyUs.point6Title": "ESG és felelős marketing",
    "about.whyUs.point6Body": "Nem fogadunk el olyan megbízást, amelyik etikailag kérdéses (greenwashing, megtévesztő ígéretek). Az EU Green Claims Directive 2026-os követelményeit már most beleépítjük az ügyfél-kommunikációba.",
    "about.valuesTitle": "Amiben hiszünk",
    "about.teamLabel": "Csapat",
    "about.teamTitle": "Kik vagyunk?",
    "about.finalCta.title": "Dolgozzunk együtt!",
    "about.finalCta.desc": "Kérj ingyenes marketing auditot vagy foglalj 30 perces ismerkedő konzultációt. 1-2 munkanapon belül válaszolunk.",
    // 404 / Not Found page
    "notfound.seoTitle": "404 – Az oldal nem található | G2A Marketing",
    "notfound.seoDesc": "Ez a tartalom nem létezik vagy elköltözött. Lépj vissza a főoldalra vagy folytasd egy javasolt szolgáltatáshoz.",
    "notfound.label": "404 · Eltört kapcsolat",
    "notfound.title1": "Ez az oldal",
    "notfound.title2": "nem található",
    "notfound.subtitle": "Az URL elavult, hibás vagy a tartalom időközben elköltözött. Vissza a főoldalra, vagy nézd meg az alábbi javaslatokat.",
    "notfound.ctaHome": "Főoldal",
    "notfound.ctaBack": "Vissza",
    "notfound.suggestionsLabel": "Talán ezeket keresed",
    "notfound.suggestHome": "Főoldal",
    "notfound.suggestServices": "Szolgáltatások",
    "notfound.suggestReferences": "Referenciák",
    "notfound.suggestContact": "Kapcsolat",
    // Process / methodology
    "process.label": "Hogyan dolgozunk",
    "process.title": "4 lépéses módszertan",
    "process.subtitle": "Strukturált folyamat — átláthatóan, mérhető eredményekkel.",
    "process.step1.title": "Audit",
    "process.step1.desc": "Mély elemzés a jelenlegi marketing teljesítményről, versenytársakról és a piacról.",
    "process.step2.title": "Stratégia",
    "process.step2.desc": "Egyedi roadmap, mérhető célokkal és csatornaspecifikus taktikával.",
    "process.step3.title": "Megvalósítás",
    "process.step3.desc": "Heti sprintek, gyors iteráció — hirdetések, tartalom, fejlesztés egy kézben.",
    "process.step4.title": "Mérés",
    "process.step4.desc": "Havi riportok, A/B tesztek, folyamatos optimalizálás — világos ROI.",
    // Industry landing page (chrome)
    "iparagi.label": "Iparági specializáció",
    "iparagi.notFound": "Az oldal nem található",
    "iparagi.backHome": "Vissza a főoldalra",
    "iparagi.challengesLabel": "Kihívások",
    "iparagi.challengesTitle": "Milyen kihívásokkal szembesülsz?",
    "iparagi.solutionsLabel": "Megoldásaink",
    "iparagi.solutionsTitle": "Hogyan segítünk?",
    "iparagi.caseStudyLabel": "Esettanulmány",
    "iparagi.caseStudyTitle": "Valós eredmény ebből az iparágból",
    "iparagi.caseClient": "Ügyfél",
    "iparagi.caseProblem": "Kihívás",
    "iparagi.caseSolution": "Megoldás",
    "iparagi.caseResult": "Eredmény",
    "iparagi.introLabel": "A piaci helyzet",
    "iparagi.whyG2ALabel": "Miért G2A?",
    "iparagi.whyG2ATitle": "Iparági tapasztalat, valós projektek",
    "iparagi.relatedServicesLabel": "Kapcsolódó szolgáltatások",
    "iparagi.relatedServicesTitle": "Mely szolgáltatásaink relevánsak ezen iparágban",
    "iparagi.faqsLabel": "Gyakori kérdések",
    "iparagi.faqsTitle": "Gyakori kérdések ebben az iparágban",
    "iparagi.finalCtaTitle": "Készen állsz a növekedésre?",
    "iparagi.finalCtaDesc": "Kérj ingyenes marketing auditot és megmutatjuk, hogyan érhetünk el hasonló eredményeket a te vállalkozásodban.",
    // Service detail page
    "service.notFound": "Szolgáltatás nem található",
    "service.backToServices": "Vissza a szolgáltatásokhoz",
    "service.labelPrefix": "Szolgáltatás",
    "service.contentComingSoon": "Tartalom hamarosan elérhető.",
    "service.formTitle": "Érdeklődj most!",
    "service.formSubtitle": "Ingyenes konzultáció a(z) {title} szolgáltatásról.",
    "service.otherServices": "Egyéb szolgáltatásaink",
    "service.fullNamePlaceholder": "Teljes neved",
    "service.messagePlaceholder": "Írd le kérdésed...",
    // Footer
    "footer.tagline": "Adatvezérelt, kreatív online marketing ügynökség. Segítünk márkádnak kiemelkedni a digitális térben.",
    "footer.contactHeader": "Elérhetőség",
    "footer.companyHeader": "Vállalat",
    "footer.admin": "Admin",
    // NewServicePage chrome
    "newservice.callUs": "Hívj minket",
    "newservice.benefitsTitle": "Mit kapsz tőlünk?",
    "newservice.processTitle": "Hogyan dolgozunk?",
    "newservice.contactTitle": "Vegyük fel a kapcsolatot!",
    "newservice.contactHint24h": "Töltsd ki az alábbi űrlapot, és 24 órán belül felvesszük veled a kapcsolatot egy ingyenes konzultáció egyeztetéséhez.",
    "newservice.thankYou": "Köszönjük!",
    "newservice.willContact": "Hamarosan felvesszük veled a kapcsolatot.",
    "newservice.messagePlaceholder": "Érdeklődöm a {title} szolgáltatás iránt...",
    "newservice.nameExample": "Kovács János",
    "newservice.emailExample": "kovacs@ceg.hu",
    // Case study detail
    "cs.notFound": "Esettanulmány nem található",
    "cs.projectData": "Projekt adatok",
    "cs.industryLabel": "Iparág",
    "cs.similarResultsTitle": "Hasonló eredményeket szeretnél?",
    "cs.similarResultsDesc": "Kérj ingyenes konzultációt és megmutatjuk, hogyan érhetünk el mérhető növekedést a te vállalkozásodban.",
    // Partners / Technology / Expertise extras
    "partners.seoTitle": "Partnereink – G2A Marketing Pécs",
    "partners.seoDesc": "Büszkék vagyunk arra, hogy számos sikeres vállalkozás bízta ránk digitális marketing feladatait.",
    "partners.nextStoryTitle": "Légy a következő sikertörténetünk!",
    "technology.seoDesc": "A legmodernebb marketing és AI eszközöket alkalmazzuk, hogy ügyfeleink mindig a legjobb eredményeket kapják.",
    // SEO Audit Page
    "seoAudit.seoTitle": "Ingyenes SEO Audit – Weboldal Elemzés | G2A Marketing",
    "seoAudit.seoDesc": "Kérd az ingyenes SEO audit eszközünket! 10 pontos ellenőrzés: meta tagek, sebesség, mobilbarát megjelenés, strukturált adatok és backlinkek. Azonnali diagnózis.",
    "seoAudit.heroLabel": "Ingyenes Eszköz",
    "seoAudit.heroTitle1": "Ingyenes",
    "seoAudit.heroTitle2": "SEO Audit",
    "seoAudit.heroTitle3": "– Tudd meg, miért nem rangsorol a weboldalad!",
    "seoAudit.heroDesc": "10 pontos ellenőrzőlistánk azonnal megmutatja, hol veszíted el a Google forgalmat. Ingyenes, azonnali, konkrét javaslatok.",
    "seoAudit.tag1": "100% ingyenes",
    "seoAudit.tag2": "Azonnali eredmény",
    "seoAudit.tag3": "Nincs kötelezettség",
    "seoAudit.submittedTitle": "Audit kérés elküldve!",
    "seoAudit.submittedDesc": "24 órán belül elküldjük a részletes SEO audit jelentést a {email} email címre.",
    "seoAudit.bookConsultation": "Konzultáció foglalása",
    "seoAudit.formTitle": "Kérd az ingyenes SEO auditot",
    "seoAudit.formHint": "Add meg a weboldalad URL-jét és email címed – 24 órán belül elküldjük a részletes elemzést.",
    "seoAudit.urlLabel": "Weboldal URL",
    "seoAudit.emailLabel": "Email cím",
    "seoAudit.submitting": "Elemzés folyamatban...",
    "seoAudit.submit": "SEO Audit kérése",
    "seoAudit.privacyNote": "Adataidat bizalmasan kezeljük. Spam-mentes.",
    "seoAudit.checksLabel": "10 Pontos Ellenőrzés",
    "seoAudit.checksTitle": "Mit vizsgál az SEO audit?",
    "seoAudit.checksDesc": "Szakértőink minden kritikus SEO tényezőt megvizsgálnak, és prioritizált fejlesztési javaslatokat adnak.",
    "seoAudit.benefitsLabel": "Miért érdemes?",
    "seoAudit.benefitsTitle": "Az audit előnyei",
    "seoAudit.ctaTitle": "Készen állsz a növekedésre?",
    "seoAudit.ctaDesc": "Az ingyenes SEO audit az első lépés a több organikus forgalom és magasabb konverzió felé.",
    // Audit Page (full marketing audit)
    "auditPage.seoTitle": "Ingyenes Marketing Audit – G2A Marketing | Weboldal & SEO Elemzés",
    "auditPage.seoDesc": "Kérj ingyenes marketing auditot! Megvizsgáljuk a weboldaladat, SEO jelenlétét, hirdetési kampányaidat és megmutatjuk, hol veszítesz el ügyfeleket. Teljesen ingyenes.",
    "auditPage.heroTitle1": "Ingyenes",
    "auditPage.heroTitle2": "Marketing Audit",
    "auditPage.heroDesc": "Megvizsgáljuk a teljes online jelenlétedet és megmutatjuk, hol veszítesz el ügyfeleket – teljesen ingyenesen, kötelezettség nélkül.",
    "auditPage.tag1": "100% ingyenes",
    "auditPage.tag2": "24h válaszidő",
    "auditPage.tag3": "Kötelezettség nélkül",
    "auditPage.includesLabel": "Mit tartalmaz?",
    "auditPage.includesTitle": "Az audit tartalma",
    "auditPage.processLabel": "Folyamat",
    "auditPage.processTitle": "Hogyan zajlik?",
    "auditPage.formLabel": "Kérés",
    "auditPage.formTitle": "Kérd az ingyenes auditot",
    "auditPage.formHint": "Töltsd ki az alábbi űrlapot és 24 órán belül felvesszük veled a kapcsolatot.",
    "auditPage.successTitle": "Köszönjük a kérést!",
    "auditPage.successDesc": "24 órán belül felvesszük veled a kapcsolatot az audit részleteivel kapcsolatban.",
    "auditPage.backHome": "Vissza a főoldalra",
    "auditPage.fieldName": "Teljes név",
    "auditPage.fieldCompany": "Cég neve",
    "auditPage.companyPlaceholder": "Cég neve",
    "auditPage.fieldWebsite": "Weboldal URL",
    "auditPage.challengesLabel": "Miben segíthetünk? (opcionális)",
    "auditPage.challengesPlaceholder": "Pl.: Növelni szeretnénk az organikus forgalmat és csökkenteni a hirdetési költségeket...",
    "auditPage.errorMsg": "Hiba történt. Kérjük, próbáld újra vagy írj nekünk emailt.",
    "auditPage.privacyNote": "Az adataidat bizalmasan kezeljük. Részletek az",
    "auditPage.privacyLink": "Adatvédelmi irányelvekben",
    // WeChat modal
    "wechat.scanFriend": "Olvasd be a QR-t a hozzáadáshoz",
  },

  en: {
    // Navigation
    "nav.services": "Services",
    "nav.expertise": "Expertise",
    "nav.technology": "Technology",
    "nav.partners": "Partners",
    "nav.blog": "Blog",
    "nav.about": "About Us",
    "nav.references": "References",
    "nav.contact": "Contact",
    "nav.freeAudit": "Free Audit",
    "nav.industries": "Industries",
    "nav.newsletter": "Newsletter",
    "nav.career": "Careers",

    // Services
    "service.localization": "Localization",
    "service.branding": "Brand Design",
    "service.ads": "Ad Management",
    "service.social": "Social Media",
    "service.strategy": "Strategic Marketing",
    "service.seo": "SEO",
    "service.webdev": "Web Development",
    "service.aiMarketing": "AI Marketing",
    "service.ppc": "PPC / Google Ads",
    "service.meta": "Meta Ads",
    "service.content": "Content Marketing",
    "service.automation": "Marketing Automation",
    "service.esg": "ESG Communication",
    "service.employerBranding": "Employer Branding",
    "service.international": "International Marketing",

    // Industries
    "industry.healthcare": "Healthcare",
    "industry.beauty": "Beauty Industry",
    "industry.engineering": "Engineering Firms",
    "industry.automotive": "Automotive",
    "industry.legal": "Law Firms",
    "industry.technology": "Technology",
    "industry.government": "Government",
    "industry.b2b": "B2B Companies",

    // Hero
    "hero.badge": "Data-Driven Marketing Agency",
    "hero.title1": "We grow your business'",
    "hero.title2": "digital presence",
    "hero.subtitle": "Strategic marketing solutions that deliver real results. SEO, advertising, social media and web development – all in one place.",
    "hero.cta1": "Free Consultation",
    "hero.cta2": "Our References",

    // Common
    "common.readMore": "Read More",
    "common.contactUs": "Contact Us",
    "common.freeAudit": "Request Free Audit",
    "common.learnMore": "Learn More",
    "common.allServices": "All Services",
    "common.back": "Back",
    "common.send": "Send",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.message": "Message",
    "common.company": "Company Name",
    "common.website": "Website",
    "common.loading": "Loading...",
    "common.success": "Successfully sent!",
    "common.error": "An error occurred. Please try again.",
    "common.close": "Close",
    "search.title": "Search",
    "search.placeholder": "Search articles and case studies...",
    "search.minChars": "Type at least 2 characters to search.",
    "search.noResults": "No results for \"{q}\"",
    "search.navigate": "navigate",
    "search.open": "open",
    "search.close": "close",
    "search.openShortcut": "Search (Ctrl+K)",
    "cookie.message": "This site only uses cookies when you explicitly request something (e.g. booking a slot via Calendly). Basic visitor analytics is cookie-free via Plausible.",
    "cookie.link": "Privacy policy",
    "cookie.accept": "Accept",
    "cookie.decline": "Decline",
    "cookie.close": "Close",
    "cookie.title": "Cookie consent",
    "cookie.acceptAll": "Accept all",
    "cookie.rejectAll": "Necessary only",
    "cookie.customize": "Customise preferences",
    "cookie.savePreferences": "Save preferences",
    "cookie.alwaysOn": "Always on",
    "cookie.cat.necessary": "Necessary",
    "cookie.cat.necessary.desc": "Required for basic site functionality (admin login, theme, consent memory). Cannot be disabled.",
    "cookie.cat.functional": "Functional",
    "cookie.cat.functional.desc": "Enhance UX without being essential (language preference memory, UI fine-tuning).",
    "cookie.cat.thirdParty": "Embedded services",
    "cookie.cat.thirdParty.desc": "The Calendly booking widget. Won't load without consent — you can also reach us directly by email.",
    "cookie.cat.marketing": "Marketing",
    "cookie.cat.marketing.desc": "Advertising, targeting and statistics cookies. We don't use any currently, but you can pre-set your preference.",
    "common.required": "Required field",

    // Newsletter
    "newsletter.emailLabel": "Email",
    "newsletter.emailPlaceholder": "you@company.com",
    "newsletter.nameLabel": "First name",
    "newsletter.namePlaceholder": "e.g. Anna",
    "newsletter.namePlaceholderRequired": "First name",
    "newsletter.topics.legend": "Which topics interest you?",
    "newsletter.topics.help": "You'll only get newsletters on the selected topics. Pick at least one — you can change this anytime.",
    "newsletter.topics.selectAll": "Select all",
    "newsletter.topics.deselectAll": "Deselect all",
    "newsletter.topics.strategy.label": "B2B marketing strategy",
    "newsletter.topics.strategy.desc": "Positioning, ICP, brand-building, GTM",
    "newsletter.topics.ai.label": "AI & automation",
    "newsletter.topics.ai.desc": "AI tooling, prompt recipes, workflow tips",
    "newsletter.topics.paid.label": "SEO & paid media",
    "newsletter.topics.paid.desc": "Google Ads, Meta, organic SEO",
    "newsletter.topics.case_studies.label": "Case studies & data",
    "newsletter.topics.case_studies.desc": "Anonymised client projects, real numbers",
    "newsletter.submit": "Subscribe",
    "newsletter.submitting": "Subscribing...",
    "newsletter.success": "Subscribed! Check your inbox for the welcome email.",
    "newsletter.error": "Something went wrong. Please try again later.",
    "newsletter.consent.before": "I consent to G2A Marketing Bt. sending me marketing emails. Details in the",
    "newsletter.consent.linkText": "privacy policy",
    "newsletter.consent.after": "; I can unsubscribe in one click anytime.",
    "newsletter.benefits.0": "One email a week — never more",
    "newsletter.benefits.1": "Concrete B2B tactics, AI tooling, case studies",
    "newsletter.benefits.2": "One-click unsubscribe",
    "newsletter.benefits.3": "We never share your data with third parties",
    "newsletter.bandLabel": "Newsletter",
    "newsletter.bandTitle": "One weekly email on B2B marketing",
    "newsletter.bandSubtitle": "Friday mornings: 1 strategic thought + 1 concrete tactic + 1 usable tool. Spam-free.",
    "newsletter.bandFinePrint": "Subscribing means you accept the privacy policy. One-click unsubscribe.",
    "newsletter.popup.title": "Stay in the loop",
    "newsletter.popup.subtitle": "One weekly email on B2B marketing trends, AI tooling and practical tactics. Spam-free — one-click unsubscribe.",
    "newsletter.popup.dismiss": "Not now",

    // Footer
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms",
    "footer.cookieSettings": "Cookie settings",
    "footer.impressum": "Imprint",
    "footer.impressum.address": "Registered office",
    "footer.impressum.regNumber": "Company reg. no.",
    "footer.impressum.taxNumber": "Tax no.",
    "footer.orBookSlot": "or",
    "footer.bookSlotLink": "book a 30-min slot",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.workingHours": "Working Hours",
    "footer.workingHoursValue": "Mon–Fri: 08:00–17:00",

    // Contact
    "contact.title": "Contact — let's talk",
    "contact.subtitle": "We'd love to hear about your ideas and challenges: new website project, ad strategy, AI integration, or any marketing question. Fill in the form, send an email, or book a free 30-minute consultation — we respond within 1–2 business days.",
    "contact.formTitle": "Send Us a Message",
    "contact.subject": "Subject",
    "contact.send": "Send Message",

    // Blog
    "blog.title": "Marketing News & Tips",
    "blog.subtitle": "Up-to-date content from the world of digital marketing.",
    "blog.readMore": "Read More",
    "blog.allCategories": "All Categories",
    "blog.latestPosts": "Latest Posts",

    // About
    "about.title": "About Us",
    "about.subtitle": "A data-driven marketing agency that delivers real results.",

    // References
    "references.title": "References & Case Studies",
    "references.subtitle": "Real results from real clients.",
    "references.challenge": "Challenge",
    "references.solution": "Solution",
    "references.results": "Results",
    "references.all": "All",

    // Audit
    "audit.title": "Free Marketing Audit",
    "audit.subtitle": "Find out what's holding back your business growth.",
    "audit.cta": "Request Audit",
    "audit.currentChallenges": "Current Challenges",
    "audit.currentBudget": "Current Marketing Budget",
    "audit.website": "Website URL",

    // Cookie
    // Expertise page
    "expertise.sectionLabel": "Specialties",
    "expertise.title": "Industries we know inside out",
    "expertise.desc": "Our experience spans many sectors. We understand the specific challenges and opportunities of each market.",
    // Partners page
    "partners.sectionLabel": "References",
    "partners.title": "Our Partners & References",
    "partners.desc": "We are proud that many successful businesses have entrusted us with their digital marketing.",
    "partners.visitWebsite": "Visit Website",
    // Technology page
    "technology.sectionLabel": "Tools",
    "technology.title": "Technologies we use",
    "technology.desc": "We use the most advanced marketing and AI tools to ensure our clients always get the best results.",
    // Services page
    "services.sectionLabel": "What we offer",
    "services.title": "Full-service digital marketing solutions",
    "services.desc": "Everything your business needs for digital success – all in one place.",
    // About page extra
    "about.sectionLabel": "About Us",
    "about.tagline": "Strategic partners in your growth",
    "about.desc": "Since 2022, we have been helping B2B companies achieve measurable marketing results.",
    "about.founded": "Founded",
    "about.team": "Our Team",
    "about.values": "Our Values",
    "about.milestones": "Milestones",
    // References page extra
    "references.sectionLabel": "Case Studies",
    "references.viewDetails": "View Details",
    "references.filterAll": "All Industries",
    "references.readMore": "Full Case Study",
    "references.back": "Back to References",
    // Blog page extra
    "blog.sectionLabel": "Blog",
    "blog.allPosts": "All",
    "blog.noResults": "No articles found in this category.",
    "blog.emptyTitle": "No articles yet",
    "blog.emptyDesc": "Fresh marketing content coming soon.",
    "blog.emptyCategoryTitle": "No articles in this category",
    "blog.emptyCategoryDesc": "Try a different category or browse all articles.",
    "blog.viewAllPosts": "All articles",
    "blog.read": "Read",
    // Audit page extra
    "audit.sectionLabel": "Free offer",
    "audit.submit": "Request Audit – Completely Free",
    "audit.submitting": "Sending...",
    // SEO Audit page
    "seoAudit.title": "Free SEO Audit",
    "seoAudit.subtitle": "Find out what's blocking your Google rankings",
    "seoAudit.placeholder": "https://yourcompany.com",
    "seoAudit.cta": "Request Free SEO Audit",
    // Popup
    "popup.title": "Before you leave...",
    "popup.desc": "Request your free marketing audit and find out how to grow your revenue by 30%!",
    "popup.cta": "Yes, I want the free audit!",
    "popup.decline": "No, thanks",
    // Sticky CTA
    "stickyCta.text": "Free Audit",
    // Nav extras
    "nav.home": "Home",
    "nav.viewAllServices": "View all services",
    "nav.freeAuditFull": "Free Marketing Audit",
    // Service descriptions (nav dropdown)
    "service.localization.desc": "Multilingual marketing",
    "service.branding.desc": "Brand identity",
    "service.ads.desc": "PPC & Meta Ads",
    "service.social.desc": "Social media management",
    "service.strategy.desc": "Full marketing strategy",
    "service.seo.desc": "SEO & content marketing",
    "service.webdev.desc": "Modern websites",
    "service.aiMarketing.desc": "AI-powered solutions",
    "service.automation.desc": "Workflow automation",
    "service.esg.desc": "Sustainability marketing",
    "service.employerBranding.desc": "Employer brand building",
    "service.international.desc": "Global presence",
    // Industries (extras)
    // Contact page
    "contact.directContact": "Direct contact",
    "contact.address": "Address",
    "contact.addressValue": "Pécs, Hungary",
    "contact.formName": "Your name",
    "contact.formEmail": "Your email",
    "contact.formPhone": "Phone (optional)",
    "contact.formCompany": "Company (optional)",
    "contact.formSubject": "Subject",
    "contact.formMessage": "Message",
    "contact.sending": "Sending...",
    "contact.successTitle": "Message sent!",
    "contact.successDesc": "Thank you for reaching out! We'll get back to you shortly.",
    "contact.errorMsg": "An error occurred while sending the message. Please try again.",
    "contact.wechatTitle": "For Chinese-market partners",
    "contact.wechatDesc": "Our managing director, Attila Győrfi, regularly works on Chinese-market projects as a guest lecturer at the University of Warsaw and an international marketing specialist. For Chinese market-entry or localisation consulting, he's reachable on WeChat for fast responses — scan the QR code.",
    "contact.wechatScan": "Scan the QR code",
    "contact.contactInfo": "Contact Information",
    "contact.formHint24h": "Fill out the form and we'll get back to you within 24 hours.",
    "contact.sendAnother": "Send another message",
    "contact.subjectPlaceholder": "How can we help?",
    "contact.messagePlaceholder": "Describe how we can help...",
    "contact.location": "Location",
    "contact.messageSentToast": "Message received! We'll contact you soon.",
    "contact.errorMessageMin": "Message must be at least 10 characters.",
    "contact.calendlyTitle": "Or book a slot directly",
    "contact.calendlyDesc": "30-minute discovery call — free, no obligation, your time slot.",
    "contact.calendlyHintAfterAudit": "💡 Or book a free 30-minute consultation now:",
    "contact.seoTitle": "Contact – G2A Marketing",
    "contact.seoDesc": "Contact G2A Marketing. Phone: +36301902575, Email: info@g2amarketing.hu. Working hours: Mon–Fri 08:00–17:00.",
    // Services page
    "services.seoTitle": "Services – G2A Marketing",
    "services.details": "Details",
    "services.freeConsultationCta": "Request a free consultation!",
    // Technology page
    "technology.seoTitle": "Technology – G2A Marketing",
    // Date locale tag
    "common.dateLocale": "en-GB",
    // Home page
    "home.hero.badge": "Strategic partner for SMBs and B2B companies",
    "home.hero.title1": "Strategic marketing,",
    "home.hero.title2": "measurable growth",
    "home.hero.subtitle": "We solve business problems. G2A Marketing is the strategic and technology partner that builds a data-driven marketing system for your business — from research to execution. Our experienced team combines creativity, analytics and artificial intelligence so your company achieves sustainable growth.",
    "home.stats.projects": "Successful projects",
    "home.stats.industries": "Industries",
    "home.stats.countries": "Countries",
    "home.stats.clients": "Satisfied clients",
    "home.stats.partners": "Active partners",
    "home.stats.foundedSince": "Founded",
    "home.targetAudience.label": "Our Target Audience",
    "home.targetAudience.title": "Who do we help?",
    "home.targetAudience.desc": "From SMEs to enterprises, from healthcare to automotive – proven expertise in 8+ industries",
    "home.solutions.label": "Solutions",
    "home.solutions.title": "What is your challenge?",
    "home.solutions.desc": "We don't think in traditional categories – we start from your business challenges",
    "home.allReferences": "All references",
    "home.cases.label": "References",
    "home.cases.title": "Real results from real clients",
    "home.cases.subtitle": "We don't make promises — we show proof. A glimpse of what we've built with our partners.",
    "home.hero.scrollHint": "Scroll",
    "home.solutions.viewSolution": "View solution",
    "home.ai.label": "AI & Innovation",
    "home.ai.title": "How we use AI",
    "home.ai.desc": "AI isn't the future — it's our daily tool. It's integrated into every workflow so we can move faster and more efficiently for our clients.",
    "home.ai.cta": "AI marketing solutions",
    "home.whyUs.label": "Why G2A?",
    "home.whyUs.title": "Why choose us",
    "home.whyUs.desc": "We're not just an agency — we're strategic partners in your growth",
    "home.newsletter.emailPlaceholder": "Email address",
    "home.newsletter.success": "Successfully subscribed!",
    "home.audit.thanks": "Thank you!",
    "home.audit.thanksDesc": "We'll get in touch within 24 hours.",
    "home.audit.namePlaceholder": "John Smith",
    "home.audit.companyLabel": "Company name",
    "home.audit.companyPlaceholder": "Acme Ltd.",
    "home.audit.messageLabel": "Brief description (optional)",
    "home.audit.messagePlaceholder": "How can we help?",
    "home.audit.submit": "Request audit — Free",
    "home.audit.submitting": "Sending…",
    "common.tryAgainError": "Something went wrong. Please try again.",
    "references.heroTitle1": "Real results,",
    "references.heroTitle2": "from real clients",
    "references.heroDesc": "We don't make promises — we deliver proof. Here are a few client case studies with measurable results.",
    "references.badge.partners": "23+ partners",
    "references.badge.industries": "8+ industries",
    "references.badge.results": "Measurable results",
    "references.empty.allTitle": "No published case studies yet",
    "references.empty.allDesc": "New case studies are in the works — meanwhile, let's talk about your project.",
    "references.empty.industryTitle": "No case study in this industry yet",
    "references.empty.industryDesc": "Try a different industry, or browse all case studies.",
    "references.empty.viewAll": "All case studies",
    "references.statsLabel": "By the numbers",
    "references.statsTitle": "Our results, aggregated",
    "references.stats.partners": "Active partners",
    "references.stats.industries": "Industries",
    "references.stats.traffic": "Average traffic growth",
    "references.stats.roas": "Average ROAS",
    "references.finalCta.title": "You could be the next success story",
    "references.finalCta.desc": "Request a free marketing audit and we'll show you how to achieve similar results for your business.",
    "references.contactCta": "Get in touch",
    "cs.startYear": "Start year",
    "cs.links": "Links",
    "blog.notFoundDesc": "It may have moved or hasn't been published yet. Head back to the article list.",
    "blog.minRead": "min read",
    "nav.openMenu": "Menu",
    "nav.logoAlt": "G2A Marketing logo",
    "nav.closeButton": "Close",
    "common.loading2": "Loading",
    "home.audit.desc": "We examine your entire online presence and show you where you are losing customers – completely free.",
    "home.audit.cta": "Request the free audit",
    "home.audit.followup": "We will contact you within 24 hours.",
    "home.testimonials.label": "Testimonials",
    "home.testimonials.title": "What do our clients say?",
    "home.faq.label": "FAQ",
    "home.faq.title": "Frequently Asked Questions",
    "home.newsletter.label": "Newsletter",
    "home.newsletter.title": "Marketing trends, every week",
    "home.newsletter.desc": "Subscribe to our newsletter and receive weekly marketing tips, case studies and AI updates.",
    "home.newsletter.submit": "Subscribe",
    "home.newsletter.submitting": "Subscribing...",
    "home.newsletter.morePrefs": "More preferences (topic selection)",
    "home.finalCta.title": "Ready to grow?",
    "home.finalCta.desc": "Contact us and let's start working together with a free consultation.",
    "common.projectsSuffix": "projects",
    // About page
    "about.seoTitle": "About – G2A Marketing | Data-driven B2B Marketing Agency",
    "about.seoDesc": "Meet the G2A Marketing team. Since 2022 we've helped B2B companies achieve measurable marketing results. Strategic thinking, AI-powered solutions, 23+ active partners.",
    "about.heroTitle1": "Strategic partners in your",
    "about.heroTitle2": "growth",
    "about.heroDesc": "Since 2022, we've been helping B2B companies achieve measurable marketing results. We aren't just an agency — we're strategic partners for long-term growth.",
    "about.stats.founded": "Founded",
    "about.stats.partners": "Active partners",
    "about.stats.industries": "Industries",
    "about.stats.years": "Active years",
    "about.stats.commitment": "Commitment",
    "about.story.label": "Our story",
    "about.story.title": "How it started",
    "about.story.p1": "G2A Marketing was founded in 2022 in Pécs with the goal of making the kind of data-driven, strategic marketing approach previously reserved for large corporations accessible to Hungarian SMEs and B2B companies. Founder Attila Győrfi, a former student and now guest lecturer at the University of Pécs Faculty of Economics, saw the market gap directly: most domestic companies were either paying too much for a Budapest agency or doing no marketing at all — meanwhile traffic was moving online.",
    "about.story.p2": "Focused specialisation has defined us from day one: our first 10 partners came from healthcare and the beauty industry, where regulatory and visual challenges meet. In 2023 we expanded to automotive and hospitality (Honda, Nissan, Café Frei, Tüke Busz). In 2024 the operational integration of AI tools became the core of our strategy — Claude, ChatGPT, Manus and Midjourney are daily tools today. By 2025 we have 23+ active partners across 8 industries — every one with real, measurable results.",
    "about.story.p3": "We don't want to be the largest agency in Hungary. We want our partners to be able to say \"we worked with them — we grew, and so did they.\" That's our goal, and that's what we measure annually.",
    "about.story.cta": "Let's work together",
    "about.mission.label": "Mission and vision",
    "about.mission.title": "What we work for",
    "about.mission.missionTitle": "Mission",
    "about.mission.missionBody": "As a strategic and technology partner, we help Hungarian SMEs and B2B companies build a data-driven marketing system — from research to execution. We believe marketing isn't a cost, it's an investment with measurable return — when done right.",
    "about.mission.visionTitle": "Vision",
    "about.mission.visionBody": "We want to be the agency where Hungarian mid-market professionals will still find it worthwhile to work with us in 5 years — because for us AI doesn't replace expertise, it amplifies it. By 2030 we aim to be the most authoritative voice in Central European B2B and SMB marketing.",
    "about.whyUs.label": "Why G2A?",
    "about.whyUs.title": "What sets us apart?",
    "about.whyUs.point1Title": "Strategy, not just campaigns",
    "about.whyUs.point1Body": "Before launching any campaign we run an audit + market research + KPI framework. If you think marketing is \"a few nice posts\", we're not the right fit.",
    "about.whyUs.point2Title": "Measurable results, not promises",
    "about.whyUs.point2Body": "Every client gets a HubSpot/GA4/Looker Studio dashboard. We baseline in month one, then growth (or its absence) is visible monthly — and we adjust accordingly.",
    "about.whyUs.point3Title": "AI deeply integrated",
    "about.whyUs.point3Body": "We don't just preach AI — we use Claude, ChatGPT, Manus, Midjourney, Runway, ElevenLabs daily. This experience translates into a 30-50% faster content pipeline for our clients.",
    "about.whyUs.point4Title": "Long-term partnership",
    "about.whyUs.point4Body": "Average client relationship is 18+ months. We don't want to be a quick-project shop. Those who start with us typically stay after a 3-month pilot.",
    "about.whyUs.point5Title": "Pécs roots, international perspective",
    "about.whyUs.point5Body": "Based in Pécs, with Hungarian and international clients. Our managing director is a guest lecturer at the University of Warsaw — with direct connections to Polish, Czech and Chinese markets.",
    "about.whyUs.point6Title": "ESG and responsible marketing",
    "about.whyUs.point6Body": "We don't take ethically questionable engagements (greenwashing, misleading promises). EU Green Claims Directive 2026 requirements are already built into our client communications.",
    "about.valuesTitle": "What we believe in",
    "about.teamLabel": "Team",
    "about.teamTitle": "Who we are",
    "about.finalCta.title": "Let's work together!",
    "about.finalCta.desc": "Request a free marketing audit or book a 30-minute introductory consultation. We respond within 1-2 business days.",
    // 404 / Not Found page
    "notfound.seoTitle": "404 – Page not found | G2A Marketing",
    "notfound.seoDesc": "This page doesn't exist or has moved. Head back to the homepage or continue to a suggested service.",
    "notfound.label": "404 · Broken link",
    "notfound.title1": "This page",
    "notfound.title2": "wasn't found",
    "notfound.subtitle": "The URL is outdated, mistyped, or the content has moved. Head home or pick one of the suggestions below.",
    "notfound.ctaHome": "Home",
    "notfound.ctaBack": "Go back",
    "notfound.suggestionsLabel": "You might be looking for",
    "notfound.suggestHome": "Home",
    "notfound.suggestServices": "Services",
    "notfound.suggestReferences": "References",
    "notfound.suggestContact": "Contact",
    // Process / methodology
    "process.label": "How we work",
    "process.title": "4-step methodology",
    "process.subtitle": "A structured process — transparent, with measurable outcomes.",
    "process.step1.title": "Audit",
    "process.step1.desc": "Deep analysis of current marketing performance, competitors and the market.",
    "process.step2.title": "Strategy",
    "process.step2.desc": "Tailored roadmap with measurable goals and channel-specific tactics.",
    "process.step3.title": "Execution",
    "process.step3.desc": "Weekly sprints, fast iteration — ads, content, dev all from one place.",
    "process.step4.title": "Measurement",
    "process.step4.desc": "Monthly reports, A/B tests, continuous optimisation — clear ROI.",
    // Industry landing page
    "iparagi.label": "Industry focus",
    "iparagi.notFound": "Page not found",
    "iparagi.backHome": "Back to homepage",
    "iparagi.challengesLabel": "Challenges",
    "iparagi.challengesTitle": "What challenges are you facing?",
    "iparagi.solutionsLabel": "Our solutions",
    "iparagi.solutionsTitle": "How we help",
    "iparagi.caseStudyLabel": "Case study",
    "iparagi.caseStudyTitle": "Real results from this industry",
    "iparagi.caseClient": "Client",
    "iparagi.caseProblem": "Challenge",
    "iparagi.caseSolution": "Solution",
    "iparagi.caseResult": "Result",
    "iparagi.introLabel": "Market context",
    "iparagi.whyG2ALabel": "Why G2A?",
    "iparagi.whyG2ATitle": "Industry experience, real projects",
    "iparagi.relatedServicesLabel": "Related services",
    "iparagi.relatedServicesTitle": "Which of our services apply here",
    "iparagi.faqsLabel": "FAQ",
    "iparagi.faqsTitle": "Frequently asked questions in this industry",
    "iparagi.finalCtaTitle": "Ready to grow?",
    "iparagi.finalCtaDesc": "Request a free marketing audit and we'll show you how to achieve similar results for your business.",
    // Service detail page
    "service.notFound": "Service not found",
    "service.backToServices": "Back to services",
    "service.labelPrefix": "Service",
    "service.contentComingSoon": "Content coming soon.",
    "service.formTitle": "Get in touch now!",
    "service.formSubtitle": "Free consultation about our {title} service.",
    "service.otherServices": "Our other services",
    "service.fullNamePlaceholder": "Full name",
    "service.messagePlaceholder": "Describe your question...",
    // Footer
    "footer.tagline": "Data-driven, creative online marketing agency. We help your brand stand out in the digital space.",
    "footer.contactHeader": "Contact",
    "footer.companyHeader": "Company",
    "footer.admin": "Admin",
    // NewServicePage chrome
    "newservice.callUs": "Call us",
    "newservice.benefitsTitle": "What do you get from us?",
    "newservice.processTitle": "How we work",
    "newservice.contactTitle": "Let's get in touch!",
    "newservice.contactHint24h": "Fill out the form below and we'll get back to you within 24 hours to schedule a free consultation.",
    "newservice.thankYou": "Thank you!",
    "newservice.willContact": "We'll be in touch soon.",
    "newservice.messagePlaceholder": "I'm interested in the {title} service...",
    "newservice.nameExample": "John Smith",
    "newservice.emailExample": "john@company.com",
    // Case study detail
    "cs.notFound": "Case study not found",
    "cs.projectData": "Project details",
    "cs.industryLabel": "Industry",
    "cs.similarResultsTitle": "Want similar results?",
    "cs.similarResultsDesc": "Request a free consultation and we'll show you how to achieve measurable growth for your business.",
    // Partners / Technology / Expertise extras
    "partners.seoTitle": "Our Partners – G2A Marketing",
    "partners.seoDesc": "We're proud that many successful businesses have entrusted us with their digital marketing.",
    "partners.nextStoryTitle": "Be our next success story!",
    "technology.seoDesc": "We use the most advanced marketing and AI tools to ensure our clients always get the best results.",
    // SEO Audit Page
    "seoAudit.seoTitle": "Free SEO Audit – Website Analysis | G2A Marketing",
    "seoAudit.seoDesc": "Request our free SEO audit tool! 10-point checklist: meta tags, speed, mobile experience, structured data, backlinks. Instant diagnosis.",
    "seoAudit.heroLabel": "Free Tool",
    "seoAudit.heroTitle1": "Free",
    "seoAudit.heroTitle2": "SEO Audit",
    "seoAudit.heroTitle3": "– Find out why your website isn't ranking!",
    "seoAudit.heroDesc": "Our 10-point checklist instantly shows where you're losing Google traffic. Free, immediate, actionable recommendations.",
    "seoAudit.tag1": "100% free",
    "seoAudit.tag2": "Instant results",
    "seoAudit.tag3": "No commitment",
    "seoAudit.submittedTitle": "Audit request sent!",
    "seoAudit.submittedDesc": "Within 24 hours we'll send the detailed SEO audit report to {email}.",
    "seoAudit.bookConsultation": "Book a consultation",
    "seoAudit.formTitle": "Request the free SEO audit",
    "seoAudit.formHint": "Enter your website URL and email – we'll send the detailed analysis within 24 hours.",
    "seoAudit.urlLabel": "Website URL",
    "seoAudit.emailLabel": "Email",
    "seoAudit.submitting": "Analyzing...",
    "seoAudit.submit": "Request SEO Audit",
    "seoAudit.privacyNote": "We handle your data confidentially. No spam.",
    "seoAudit.checksLabel": "10-Point Check",
    "seoAudit.checksTitle": "What does the SEO audit cover?",
    "seoAudit.checksDesc": "Our experts examine every critical SEO factor and deliver prioritized improvement recommendations.",
    "seoAudit.benefitsLabel": "Why bother?",
    "seoAudit.benefitsTitle": "Audit benefits",
    "seoAudit.ctaTitle": "Ready to grow?",
    "seoAudit.ctaDesc": "A free SEO audit is the first step toward more organic traffic and higher conversions.",
    // Audit Page
    "auditPage.seoTitle": "Free Marketing Audit – G2A Marketing | Website & SEO Analysis",
    "auditPage.seoDesc": "Request a free marketing audit! We examine your website, SEO presence and ad campaigns, and show you where you're losing customers. Completely free.",
    "auditPage.heroTitle1": "Free",
    "auditPage.heroTitle2": "Marketing Audit",
    "auditPage.heroDesc": "We examine your entire online presence and show you where you're losing customers – completely free, no commitment.",
    "auditPage.tag1": "100% free",
    "auditPage.tag2": "24h response",
    "auditPage.tag3": "No commitment",
    "auditPage.includesLabel": "What's included?",
    "auditPage.includesTitle": "Audit contents",
    "auditPage.processLabel": "Process",
    "auditPage.processTitle": "How it works",
    "auditPage.formLabel": "Request",
    "auditPage.formTitle": "Request the free audit",
    "auditPage.formHint": "Fill out the form below and we'll get back to you within 24 hours.",
    "auditPage.successTitle": "Thank you!",
    "auditPage.successDesc": "We'll contact you within 24 hours about the audit details.",
    "auditPage.backHome": "Back to homepage",
    "auditPage.fieldName": "Full name",
    "auditPage.fieldCompany": "Company",
    "auditPage.companyPlaceholder": "Company name",
    "auditPage.fieldWebsite": "Website URL",
    "auditPage.challengesLabel": "How can we help? (optional)",
    "auditPage.challengesPlaceholder": "E.g.: We'd like to grow organic traffic and lower ad spend...",
    "auditPage.errorMsg": "Something went wrong. Please try again or email us.",
    "auditPage.privacyNote": "We handle your data confidentially. Details in the",
    "auditPage.privacyLink": "Privacy Policy",
    // WeChat modal
    "wechat.scanFriend": "Scan the QR code to add me as friend",
  },

  zh: {
    // Navigation
    "nav.services": "服务",
    "nav.expertise": "专业领域",
    "nav.technology": "技术",
    "nav.partners": "合作伙伴",
    "nav.blog": "博客",
    "nav.about": "关于我们",
    "nav.references": "客户案例",
    "nav.contact": "联系我们",
    "nav.freeAudit": "免费评估",
    "nav.industries": "行业",
    "nav.newsletter": "通讯订阅",
    "nav.career": "招聘",

    // Services
    "service.localization": "本地化",
    "service.branding": "品牌设计",
    "service.ads": "广告管理",
    "service.social": "社交媒体",
    "service.strategy": "营销战略",
    "service.seo": "搜索引擎优化",
    "service.webdev": "网站开发",
    "service.aiMarketing": "AI 营销",
    "service.ppc": "PPC / Google 广告",
    "service.meta": "Meta 广告",
    "service.content": "内容营销",
    "service.automation": "营销自动化",
    "service.esg": "ESG 传播",
    "service.employerBranding": "雇主品牌",
    "service.international": "国际营销",

    // Industries
    "industry.healthcare": "医疗健康",
    "industry.beauty": "美容行业",
    "industry.engineering": "工程公司",
    "industry.automotive": "汽车行业",
    "industry.legal": "律师事务所",
    "industry.technology": "科技",
    "industry.government": "政府机构",
    "industry.b2b": "B2B 企业",

    // Hero
    "hero.badge": "数据驱动营销公司",
    "hero.title1": "助您业务",
    "hero.title2": "数字化腾飞",
    "hero.subtitle": "以战略营销方案驱动真实增长。SEO、广告、社交媒体与网站开发 —— 一站式服务。",
    "hero.cta1": "免费咨询",
    "hero.cta2": "查看案例",

    // Common
    "common.readMore": "阅读更多",
    "common.contactUs": "联系我们",
    "common.freeAudit": "申请免费评估",
    "common.learnMore": "了解更多",
    "common.allServices": "所有服务",
    "common.back": "返回",
    "common.send": "发送",
    "common.name": "姓名",
    "common.email": "邮箱",
    "common.phone": "电话",
    "common.message": "留言",
    "common.company": "公司名称",
    "common.website": "网站",
    "common.loading": "加载中...",
    "common.success": "发送成功！",
    "common.error": "发生错误，请重试。",
    "common.close": "关闭",
    "search.title": "搜索",
    "search.placeholder": "搜索文章和案例研究...",
    "search.minChars": "请输入至少 2 个字符进行搜索。",
    "search.noResults": "未找到 \"{q}\" 的结果",
    "search.navigate": "导航",
    "search.open": "打开",
    "search.close": "关闭",
    "search.openShortcut": "搜索 (Ctrl+K)",
    "cookie.message": "本网站仅在您主动操作时才使用 cookie(例如通过 Calendly 预约时间)。基础访问统计使用无 cookie 的 Plausible。",
    "cookie.link": "隐私政策",
    "cookie.accept": "接受",
    "cookie.decline": "拒绝",
    "cookie.close": "关闭",
    "cookie.title": "Cookie 同意",
    "cookie.acceptAll": "全部接受",
    "cookie.rejectAll": "仅必要",
    "cookie.customize": "自定义设置",
    "cookie.savePreferences": "保存设置",
    "cookie.alwaysOn": "始终启用",
    "cookie.cat.necessary": "必要",
    "cookie.cat.necessary.desc": "网站基本功能所需(管理员登录、主题、同意记忆)。无法禁用。",
    "cookie.cat.functional": "功能",
    "cookie.cat.functional.desc": "提升体验但非必需(语言偏好记忆、界面微调)。",
    "cookie.cat.thirdParty": "嵌入服务",
    "cookie.cat.thirdParty.desc": "Calendly 预约小工具。未同意将不加载 — 您也可直接通过电子邮件联系我们。",
    "cookie.cat.marketing": "营销",
    "cookie.cat.marketing.desc": "广告、定向与统计 Cookie。我们目前不使用,但您可以预先设置偏好。",
    "common.required": "必填项",

    // Newsletter
    "newsletter.emailLabel": "电子邮箱",
    "newsletter.emailPlaceholder": "you@company.com",
    "newsletter.nameLabel": "名字",
    "newsletter.namePlaceholder": "如 Anna",
    "newsletter.namePlaceholderRequired": "名字",
    "newsletter.topics.legend": "您对哪些话题感兴趣?",
    "newsletter.topics.help": "您仅会收到所选话题的邮件。至少选择 1 项 — 可随时调整。",
    "newsletter.topics.selectAll": "全选",
    "newsletter.topics.deselectAll": "取消全选",
    "newsletter.topics.strategy.label": "B2B 营销战略",
    "newsletter.topics.strategy.desc": "定位、ICP、品牌建设、GTM",
    "newsletter.topics.ai.label": "AI 与自动化",
    "newsletter.topics.ai.desc": "AI 工具、提示词配方、工作流技巧",
    "newsletter.topics.paid.label": "SEO 与效果广告",
    "newsletter.topics.paid.desc": "Google Ads、Meta 广告、自然 SEO",
    "newsletter.topics.case_studies.label": "案例研究与数据",
    "newsletter.topics.case_studies.desc": "匿名化客户项目与真实数据",
    "newsletter.submit": "订阅",
    "newsletter.submitting": "订阅中...",
    "newsletter.success": "订阅成功!欢迎邮件已发送到您的邮箱。",
    "newsletter.error": "出现错误,请稍后再试。",
    "newsletter.consent.before": "我同意 G2A Marketing Bt. 通过电子邮件向我发送营销内容。详见",
    "newsletter.consent.linkText": "隐私政策",
    "newsletter.consent.after": ";可随时一键退订。",
    "newsletter.benefits.0": "每周一封 — 绝不更多",
    "newsletter.benefits.1": "具体的 B2B 战术、AI 工具与案例研究",
    "newsletter.benefits.2": "一键退订",
    "newsletter.benefits.3": "绝不向第三方分享您的数据",
    "newsletter.bandLabel": "通讯",
    "newsletter.bandTitle": "每周一封 B2B 营销邮件",
    "newsletter.bandSubtitle": "周五早晨:1 个战略思考 + 1 个具体战术 + 1 款可用工具。无垃圾邮件。",
    "newsletter.bandFinePrint": "订阅即表示您接受隐私政策。一键退订。",
    "newsletter.popup.title": "保持关注",
    "newsletter.popup.subtitle": "每周一封关于 B2B 营销趋势、AI 工具与可操作战术的邮件。无垃圾邮件 — 一键退订。",
    "newsletter.popup.dismiss": "暂不",

    // Footer
    "footer.rights": "版权所有。",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.cookieSettings": "Cookie 设置",
    "footer.impressum": "公司信息",
    "footer.impressum.address": "注册地址",
    "footer.impressum.regNumber": "公司登记号",
    "footer.impressum.taxNumber": "税号",
    "footer.orBookSlot": "或",
    "footer.bookSlotLink": "预约 30 分钟时段",
    "footer.services": "服务",
    "footer.company": "公司",
    "footer.contact": "联系方式",
    "footer.workingHours": "工作时间",
    "footer.workingHoursValue": "周一至周五 08:00–17:00",

    // Contact
    "contact.title": "联系我们 — 期待沟通",
    "contact.subtitle": "我们乐于聆听您的想法与挑战:新网站项目、广告策略、AI 集成或任何营销问题。填写下方表单、发送邮件或预约 30 分钟免费咨询 — 我们将在 1–2 个工作日内回复。",
    "contact.formTitle": "给我们留言",
    "contact.subject": "主题",
    "contact.send": "发送留言",

    // Blog
    "blog.title": "营销资讯与技巧",
    "blog.subtitle": "数字营销领域的最新内容。",
    "blog.readMore": "阅读更多",
    "blog.allCategories": "所有分类",
    "blog.latestPosts": "最新文章",

    // About
    "about.title": "关于我们",
    "about.subtitle": "以数据驱动、带来真实成果的营销公司。",

    // References
    "references.title": "客户案例与故事",
    "references.subtitle": "真实客户,真实成果。",
    "references.challenge": "挑战",
    "references.solution": "解决方案",
    "references.results": "成果",
    "references.all": "全部",

    // Audit
    "audit.title": "免费营销评估",
    "audit.subtitle": "找出阻碍您业务增长的因素。",
    "audit.cta": "申请评估",
    "audit.currentChallenges": "当前挑战",
    "audit.currentBudget": "当前营销预算",
    "audit.website": "网站 URL",

    // Cookie
    // Expertise
    "expertise.sectionLabel": "专业领域",
    "expertise.title": "我们深耕的行业",
    "expertise.desc": "我们的经验覆盖多个行业,深入理解各个市场的挑战与机遇。",
    // Partners
    "partners.sectionLabel": "客户",
    "partners.title": "我们的合作伙伴",
    "partners.desc": "我们很荣幸众多成功企业将数字营销业务托付给我们。",
    "partners.visitWebsite": "访问网站",
    // Technology
    "technology.sectionLabel": "工具",
    "technology.title": "我们使用的技术",
    "technology.desc": "我们采用最先进的营销与 AI 工具,为客户带来最优成果。",
    // Services
    "services.sectionLabel": "我们的服务",
    "services.title": "全方位数字营销解决方案",
    "services.desc": "您业务数字化成功所需的一切 —— 尽在一站。",
    // About extra
    "about.sectionLabel": "关于我们",
    "about.tagline": "您增长道路上的战略伙伴",
    "about.desc": "自 2022 年起,我们助力 B2B 企业实现可衡量的营销成果。",
    "about.founded": "成立于",
    "about.team": "我们的团队",
    "about.values": "我们的价值观",
    "about.milestones": "里程碑",
    // References extra
    "references.sectionLabel": "客户案例",
    "references.viewDetails": "查看详情",
    "references.filterAll": "所有行业",
    "references.readMore": "查看完整案例",
    "references.back": "返回案例列表",
    // Blog extra
    "blog.sectionLabel": "博客",
    "blog.allPosts": "全部",
    "blog.emptyTitle": "暂无文章",
    "blog.emptyDesc": "营销领域的新鲜内容即将上线。",
    "blog.emptyCategoryTitle": "此分类暂无文章",
    "blog.emptyCategoryDesc": "请尝试其他分类,或浏览所有文章。",
    "blog.viewAllPosts": "全部文章",
    "blog.noResults": "该分类下暂无文章。",
    "blog.read": "阅读",
    // Audit extra
    "audit.sectionLabel": "免费提供",
    "audit.submit": "申请免费评估",
    "audit.submitting": "发送中...",
    // SEO Audit
    "seoAudit.title": "免费 SEO 评估",
    "seoAudit.subtitle": "找出影响您 Google 排名的因素",
    "seoAudit.placeholder": "https://yourcompany.com",
    "seoAudit.cta": "申请免费 SEO 评估",
    // Popup
    "popup.title": "离开前请稍等...",
    "popup.desc": "申请免费营销评估,了解如何将收入提升 30%！",
    "popup.cta": "好的,我要免费评估！",
    "popup.decline": "不用了,谢谢",
    // Sticky CTA
    "stickyCta.text": "免费评估",
    // Nav extras
    "nav.home": "首页",
    "nav.viewAllServices": "查看全部服务",
    "nav.freeAuditFull": "免费营销评估",
    // Service descriptions (nav dropdown)
    "service.localization.desc": "多语种营销",
    "service.branding.desc": "品牌识别",
    "service.ads.desc": "PPC 与 Meta 广告",
    "service.social.desc": "社交媒体管理",
    "service.strategy.desc": "全面营销战略",
    "service.seo.desc": "SEO 与内容营销",
    "service.webdev.desc": "现代化网站",
    "service.aiMarketing.desc": "AI 驱动的解决方案",
    "service.automation.desc": "工作流自动化",
    "service.esg.desc": "可持续发展营销",
    "service.employerBranding.desc": "雇主品牌建设",
    "service.international.desc": "全球品牌布局",
    // Industries (extras)
    // Contact page
    "contact.directContact": "直接联系方式",
    "contact.address": "地址",
    "contact.addressValue": "匈牙利佩奇",
    "contact.formName": "您的姓名",
    "contact.formEmail": "您的邮箱",
    "contact.formPhone": "电话(选填)",
    "contact.formCompany": "公司(选填)",
    "contact.formSubject": "主题",
    "contact.formMessage": "留言",
    "contact.sending": "发送中...",
    "contact.successTitle": "留言已发送!",
    "contact.successDesc": "感谢您的联系!我们会尽快回复您。",
    "contact.errorMsg": "发送留言时发生错误,请重试。",
    "contact.wechatTitle": "面向中国市场的合作伙伴",
    "contact.wechatDesc": "我们的总经理 Győrfi Attila 作为华沙大学客座讲师与国际营销专家,长期参与中国市场项目。如需中国市场进入或本地化咨询,可通过微信快速联系 — 扫描下方二维码即可添加。",
    "contact.wechatScan": "扫描二维码",
    "contact.contactInfo": "联系方式",
    "contact.formHint24h": "填写表单,我们将在 24 小时内回复您。",
    "contact.sendAnother": "再发一条留言",
    "contact.subjectPlaceholder": "需要哪方面的帮助?",
    "contact.messagePlaceholder": "请描述我们如何为您提供帮助...",
    "contact.location": "地点",
    "contact.messageSentToast": "留言已收到!我们会尽快联系您。",
    "contact.errorMessageMin": "留言至少需要 10 个字符。",
    "contact.calendlyTitle": "或直接预约时间",
    "contact.calendlyDesc": "30 分钟的免费咨询 — 无需承诺,您选择时间。",
    "contact.calendlyHintAfterAudit": "💡 或者立即预约 30 分钟的免费咨询:",
    "contact.seoTitle": "联系 G2A Marketing",
    "contact.seoDesc": "联系 G2A Marketing。电话: +36301902575, 邮箱: info@g2amarketing.hu。工作时间:周一至周五 08:00–17:00。",
    // Services page
    "services.seoTitle": "服务 – G2A Marketing",
    "services.details": "查看详情",
    "services.freeConsultationCta": "申请免费咨询！",
    // Technology page
    "technology.seoTitle": "技术 – G2A Marketing",
    // Date locale tag
    "common.dateLocale": "zh-CN",
    // Home page
    "home.hero.badge": "中小企业与 B2B 企业的战略合作伙伴",
    "home.hero.title1": "战略营销、",
    "home.hero.title2": "可衡量的增长",
    "home.hero.subtitle": "我们解决业务问题。G2A Marketing 是战略与技术伙伴,为您的企业从研究到落地打造数据驱动的营销系统。资深团队将创意、分析与人工智能相结合,助您实现可持续增长。",
    "home.stats.projects": "成功项目",
    "home.stats.industries": "行业",
    "home.stats.countries": "国家",
    "home.stats.clients": "满意客户",
    "home.stats.partners": "活跃合作伙伴",
    "home.stats.foundedSince": "成立年份",
    "home.targetAudience.label": "我们的目标客户",
    "home.targetAudience.title": "我们为谁服务?",
    "home.targetAudience.desc": "从中小企业到大型集团,从医疗健康到汽车行业 —— 8+ 行业的可靠经验",
    "home.solutions.label": "解决方案",
    "home.solutions.title": "您面临什么挑战?",
    "home.solutions.desc": "我们不拘泥于传统分类 —— 而是从您的业务挑战出发",
    "home.allReferences": "所有案例",
    "home.cases.label": "客户案例",
    "home.cases.title": "真实客户的真实成果",
    "home.cases.subtitle": "我们不做承诺 —— 我们用成果说话。看看我们与合作伙伴共同打造的项目。",
    "home.hero.scrollHint": "向下滚动",
    "home.solutions.viewSolution": "查看解决方案",
    "home.ai.label": "AI 与创新",
    "home.ai.title": "我们如何运用 AI",
    "home.ai.desc": "AI 不是未来 —— 而是我们日常的工具。它已融入我们的每一项工作流程,让我们能为客户更快、更高效地交付。",
    "home.ai.cta": "AI 营销解决方案",
    "home.whyUs.label": "为何选择 G2A?",
    "home.whyUs.title": "为何选择我们",
    "home.whyUs.desc": "我们不只是代理机构 —— 我们是您增长的战略合作伙伴",
    "home.newsletter.emailPlaceholder": "邮箱地址",
    "home.newsletter.success": "订阅成功!",
    "home.audit.thanks": "感谢您!",
    "home.audit.thanksDesc": "我们将在 24 小时内与您联系。",
    "home.audit.namePlaceholder": "张伟",
    "home.audit.companyLabel": "公司名称",
    "home.audit.companyPlaceholder": "公司有限公司",
    "home.audit.messageLabel": "简短说明(可选)",
    "home.audit.messagePlaceholder": "我们能帮您做什么?",
    "home.audit.submit": "申请评估 — 免费",
    "home.audit.submitting": "发送中…",
    "common.tryAgainError": "出现错误,请重试。",
    "references.heroTitle1": "真实客户的",
    "references.heroTitle2": "真实成果",
    "references.heroDesc": "我们不做承诺 —— 我们用成果证明。以下是几个客户案例,均带有可衡量的成果。",
    "references.badge.partners": "23+ 合作伙伴",
    "references.badge.industries": "8+ 行业",
    "references.badge.results": "可衡量的成果",
    "references.empty.allTitle": "暂无已发布的客户案例",
    "references.empty.allDesc": "新的客户案例正在准备中 —— 与此同时,聊聊您的项目吧。",
    "references.empty.industryTitle": "该行业暂无客户案例",
    "references.empty.industryDesc": "尝试其他行业,或查看所有客户案例。",
    "references.empty.viewAll": "所有客户案例",
    "references.statsLabel": "数据看板",
    "references.statsTitle": "我们的成果汇总",
    "references.stats.partners": "活跃合作伙伴",
    "references.stats.industries": "行业",
    "references.stats.traffic": "平均流量增长",
    "references.stats.roas": "平均 ROAS",
    "references.finalCta.title": "您可以成为下一个成功故事",
    "references.finalCta.desc": "申请免费营销评估,我们将向您展示如何在您的业务中实现类似成果。",
    "references.contactCta": "联系我们",
    "cs.startYear": "启动年份",
    "cs.links": "链接",
    "blog.notFoundDesc": "可能已迁移或尚未发布。返回文章列表。",
    "blog.minRead": "分钟阅读",
    "nav.openMenu": "菜单",
    "nav.logoAlt": "G2A Marketing 标志",
    "nav.closeButton": "关闭",
    "common.loading2": "加载中",
    "home.audit.desc": "我们全面评估您的在线表现,指出客户流失的环节 —— 完全免费。",
    "home.audit.cta": "申请免费评估",
    "home.audit.followup": "我们将在 24 小时内联系您。",
    "home.testimonials.label": "客户评价",
    "home.testimonials.title": "客户怎么说?",
    "home.faq.label": "常见问题",
    "home.faq.title": "常见问题解答",
    "home.newsletter.label": "订阅",
    "home.newsletter.title": "每周营销趋势",
    "home.newsletter.desc": "订阅我们的简报,每周获取营销技巧、客户案例与 AI 最新动态。",
    "home.newsletter.submit": "订阅",
    "home.newsletter.submitting": "订阅中...",
    "home.newsletter.morePrefs": "更多偏好(话题选择)",
    "home.finalCta.title": "准备好增长了吗?",
    "home.finalCta.desc": "联系我们,用一次免费咨询开启合作。",
    "common.projectsSuffix": "项目",
    // About page
    "about.seoTitle": "关于我们 – G2A Marketing | 数据驱动的 B2B 营销公司",
    "about.seoDesc": "认识 G2A Marketing 团队。自 2022 年起,我们助力 B2B 企业实现可衡量的营销成果。战略思维、AI 驱动的方案、23+ 活跃合作伙伴。",
    "about.heroTitle1": "您增长道路上的",
    "about.heroTitle2": "战略伙伴",
    "about.heroDesc": "自 2022 年起,我们助力 B2B 企业实现可衡量的营销成果。我们不只是一家营销公司 —— 而是您长期增长的战略伙伴。",
    "about.stats.founded": "成立年份",
    "about.stats.partners": "活跃伙伴",
    "about.stats.industries": "行业",
    "about.stats.years": "运营年数",
    "about.stats.commitment": "专注度",
    "about.story.label": "我们的故事",
    "about.story.title": "从何开始",
    "about.story.p1": "G2A Marketing 于 2022 年在匈牙利佩奇成立,宗旨是让原本只属于大企业的数据驱动战略营销方法,也能为匈牙利中小企业与 B2B 公司所用。创始人 Győrfi Attila 曾是佩奇大学经济学院的学生,如今是该院客座讲师 —— 他亲眼看到市场鸿沟:多数本国公司要么在为布达佩斯代理机构支付过高费用,要么完全不做营销 —— 与此同时,流量正越来越多地转向线上。",
    "about.story.p2": "从一开始我们就专注于细分:首批 10 家合作伙伴来自医疗与美容行业,这两个领域兼具监管与视觉挑战。2023 年我们扩展到汽车与餐饮(本田、日产、Café Frei、Tüke Busz)。2024 年 AI 工具的运营整合成为战略核心 —— Claude、ChatGPT、Manus 与 Midjourney 是我们的日常工具。到 2025 年,我们在 8 个行业拥有 23+ 活跃合作伙伴 —— 每一个都有真实可衡量的成果。",
    "about.story.p3": "我们不想成为匈牙利最大的代理机构。我们希望合作伙伴能说:「我们与他们一起工作 — 我们成长了,他们也成长了。」这是我们的目标,也是我们每年衡量的东西。",
    "about.story.cta": "开启合作",
    "about.mission.label": "使命与愿景",
    "about.mission.title": "我们为何工作",
    "about.mission.missionTitle": "使命",
    "about.mission.missionBody": "作为战略与技术合作伙伴,我们帮助匈牙利中小企业与 B2B 公司从研究到落地构建数据驱动的营销系统。我们相信营销不是成本 —— 当做得正确时,它是带可衡量回报的投资。",
    "about.mission.visionTitle": "愿景",
    "about.mission.visionBody": "我们希望成为匈牙利中型市场专业人士在 5 年后仍值得合作的代理机构 —— 因为对我们而言,AI 不取代专业,而是放大它。到 2030 年,我们的目标是成为中欧 B2B 与中小企业营销领域最权威的声音。",
    "about.whyUs.label": "为何选择 G2A?",
    "about.whyUs.title": "我们的与众不同之处",
    "about.whyUs.point1Title": "战略,而非活动",
    "about.whyUs.point1Body": "在启动任何活动之前,先做审计 + 市场研究 + KPI 框架。如果您认为营销是「几条好看的帖子」,那我们不是合适的合作方。",
    "about.whyUs.point2Title": "可衡量的成果,而非承诺",
    "about.whyUs.point2Body": "每位客户都获得 HubSpot/GA4/Looker Studio 仪表板。第一个月建立基线,之后每月看到增长 —— 或它的缺失,然后做出调整。",
    "about.whyUs.point3Title": "深度集成的 AI",
    "about.whyUs.point3Body": "我们不只宣传 AI —— 我们日常使用 Claude、ChatGPT、Manus、Midjourney、Runway、ElevenLabs。这种经验为客户带来 30-50% 更快的内容流水线。",
    "about.whyUs.point4Title": "长期合作伙伴关系",
    "about.whyUs.point4Body": "平均客户关系超过 18 个月。我们不想成为快速跑完即停的项目公司。与我们开始合作的客户在 3 个月试点后通常会留下。",
    "about.whyUs.point5Title": "佩奇根基,国际视野",
    "about.whyUs.point5Body": "总部在佩奇,服务匈牙利与国际客户。总经理是华沙大学客座讲师 —— 与波兰、捷克、中国市场有直接联系。",
    "about.whyUs.point6Title": "ESG 与负责任营销",
    "about.whyUs.point6Body": "我们不接受道德上有疑问的项目(漂绿、误导性承诺)。欧盟绿色声明指令 2026 要求已纳入客户沟通中。",
    "about.valuesTitle": "我们信奉的理念",
    "about.teamLabel": "团队",
    "about.teamTitle": "我们是谁",
    "about.finalCta.title": "让我们合作吧!",
    "about.finalCta.desc": "申请免费营销评估或预约 30 分钟介绍性咨询。我们将在 1-2 个工作日内回复。",
    // 404 / Not Found page
    "notfound.seoTitle": "404 – 页面未找到 | G2A Marketing",
    "notfound.seoDesc": "该页面不存在或已迁移。返回首页或前往推荐的服务页面。",
    "notfound.label": "404 · 链接已失效",
    "notfound.title1": "未能找到",
    "notfound.title2": "该页面",
    "notfound.subtitle": "URL 已失效、输入错误,或内容已迁移。返回首页,或选择以下推荐之一。",
    "notfound.ctaHome": "首页",
    "notfound.ctaBack": "返回",
    "notfound.suggestionsLabel": "您也许在找",
    "notfound.suggestHome": "首页",
    "notfound.suggestServices": "服务",
    "notfound.suggestReferences": "客户案例",
    "notfound.suggestContact": "联系我们",
    // Process / methodology
    "process.label": "我们的工作方式",
    "process.title": "四步方法论",
    "process.subtitle": "结构化流程 —— 透明、可衡量。",
    "process.step1.title": "审计",
    "process.step1.desc": "深入分析当前营销表现、竞争对手与市场环境。",
    "process.step2.title": "战略",
    "process.step2.desc": "定制化路线图,设定可衡量目标与各渠道战术。",
    "process.step3.title": "执行",
    "process.step3.desc": "每周冲刺、快速迭代 —— 广告、内容、开发一站式交付。",
    "process.step4.title": "衡量",
    "process.step4.desc": "月度报告、A/B 测试、持续优化 —— 清晰的 ROI。",
    // Industry landing page
    "iparagi.label": "行业专注",
    "iparagi.notFound": "页面未找到",
    "iparagi.backHome": "返回首页",
    "iparagi.challengesLabel": "挑战",
    "iparagi.challengesTitle": "您面临哪些挑战?",
    "iparagi.solutionsLabel": "我们的方案",
    "iparagi.solutionsTitle": "我们如何帮助您",
    "iparagi.caseStudyLabel": "客户案例",
    "iparagi.caseStudyTitle": "来自该行业的真实成果",
    "iparagi.caseClient": "客户",
    "iparagi.caseProblem": "挑战",
    "iparagi.caseSolution": "方案",
    "iparagi.caseResult": "成果",
    "iparagi.introLabel": "市场背景",
    "iparagi.whyG2ALabel": "为何选择 G2A?",
    "iparagi.whyG2ATitle": "行业经验与实际项目",
    "iparagi.relatedServicesLabel": "相关服务",
    "iparagi.relatedServicesTitle": "本行业适用的服务",
    "iparagi.faqsLabel": "常见问题",
    "iparagi.faqsTitle": "本行业的常见问题",
    "iparagi.finalCtaTitle": "准备好增长了吗?",
    "iparagi.finalCtaDesc": "申请免费营销评估,我们将向您展示如何在您的业务中实现类似成果。",
    // Service detail page
    "service.notFound": "服务未找到",
    "service.backToServices": "返回服务列表",
    "service.labelPrefix": "服务",
    "service.contentComingSoon": "内容即将上线。",
    "service.formTitle": "立即咨询！",
    "service.formSubtitle": "关于 {title} 服务的免费咨询。",
    "service.otherServices": "我们的其他服务",
    "service.fullNamePlaceholder": "您的姓名",
    "service.messagePlaceholder": "请描述您的问题...",
    // Footer
    "footer.tagline": "数据驱动的创意在线营销公司。助力您的品牌在数字领域脱颖而出。",
    "footer.contactHeader": "联系方式",
    "footer.companyHeader": "公司",
    "footer.admin": "Admin",
    // NewServicePage chrome
    "newservice.callUs": "致电我们",
    "newservice.benefitsTitle": "您能从我们这里获得什么?",
    "newservice.processTitle": "我们如何工作",
    "newservice.contactTitle": "让我们联系吧！",
    "newservice.contactHint24h": "填写下方表单,我们会在 24 小时内联系您,安排免费咨询。",
    "newservice.thankYou": "感谢您！",
    "newservice.willContact": "我们会尽快联系您。",
    "newservice.messagePlaceholder": "我对 {title} 服务感兴趣...",
    "newservice.nameExample": "张三",
    "newservice.emailExample": "zhang@company.com",
    // Case study detail
    "cs.notFound": "客户案例未找到",
    "cs.projectData": "项目详情",
    "cs.industryLabel": "行业",
    "cs.similarResultsTitle": "想获得类似成果吗？",
    "cs.similarResultsDesc": "申请免费咨询,我们将向您展示如何在您的业务中实现可衡量的增长。",
    // Partners / Technology / Expertise extras
    "partners.seoTitle": "合作伙伴 – G2A Marketing",
    "partners.seoDesc": "我们很荣幸众多成功企业将数字营销业务托付给我们。",
    "partners.nextStoryTitle": "成为下一个成功故事！",
    "technology.seoDesc": "我们采用最先进的营销与 AI 工具,为客户带来最优成果。",
    // SEO Audit Page
    "seoAudit.seoTitle": "免费 SEO 评估 – 网站分析 | G2A Marketing",
    "seoAudit.seoDesc": "申请我们的免费 SEO 评估工具！10 项检查:元标签、加载速度、移动端体验、结构化数据与反向链接。即时诊断。",
    "seoAudit.heroLabel": "免费工具",
    "seoAudit.heroTitle1": "免费",
    "seoAudit.heroTitle2": "SEO 评估",
    "seoAudit.heroTitle3": "—— 找出您网站排名不佳的原因！",
    "seoAudit.heroDesc": "我们的 10 项检查清单立即告诉您在哪里流失 Google 流量。免费、即时、可落地的建议。",
    "seoAudit.tag1": "100% 免费",
    "seoAudit.tag2": "即时结果",
    "seoAudit.tag3": "无任何承诺",
    "seoAudit.submittedTitle": "评估申请已发送！",
    "seoAudit.submittedDesc": "我们将在 24 小时内把详细的 SEO 评估报告发送至 {email}。",
    "seoAudit.bookConsultation": "预约咨询",
    "seoAudit.formTitle": "申请免费 SEO 评估",
    "seoAudit.formHint": "输入您的网站 URL 与邮箱 —— 我们将在 24 小时内发送详细分析。",
    "seoAudit.urlLabel": "网站 URL",
    "seoAudit.emailLabel": "邮箱",
    "seoAudit.submitting": "分析中...",
    "seoAudit.submit": "申请 SEO 评估",
    "seoAudit.privacyNote": "我们严格保密您的数据,不发垃圾邮件。",
    "seoAudit.checksLabel": "10 项检查",
    "seoAudit.checksTitle": "SEO 评估涵盖哪些内容?",
    "seoAudit.checksDesc": "我们的专家审查每个关键 SEO 因素,并提供优先级排序的改进建议。",
    "seoAudit.benefitsLabel": "为什么值得?",
    "seoAudit.benefitsTitle": "评估的好处",
    "seoAudit.ctaTitle": "准备好增长了吗?",
    "seoAudit.ctaDesc": "免费 SEO 评估是获得更多自然流量与更高转化率的第一步。",
    // Audit Page
    "auditPage.seoTitle": "免费营销评估 – G2A Marketing | 网站 & SEO 分析",
    "auditPage.seoDesc": "申请免费营销评估！我们检查您的网站、SEO 表现与广告活动,告诉您在哪里流失客户。完全免费。",
    "auditPage.heroTitle1": "免费",
    "auditPage.heroTitle2": "营销评估",
    "auditPage.heroDesc": "我们全面评估您的在线表现,告诉您在哪里流失客户 —— 完全免费、无承诺。",
    "auditPage.tag1": "100% 免费",
    "auditPage.tag2": "24 小时回复",
    "auditPage.tag3": "无任何承诺",
    "auditPage.includesLabel": "包含哪些内容?",
    "auditPage.includesTitle": "评估内容",
    "auditPage.processLabel": "流程",
    "auditPage.processTitle": "如何进行?",
    "auditPage.formLabel": "申请",
    "auditPage.formTitle": "申请免费评估",
    "auditPage.formHint": "填写下方表单,我们将在 24 小时内联系您。",
    "auditPage.successTitle": "感谢您的申请！",
    "auditPage.successDesc": "我们将在 24 小时内联系您,讨论评估的具体细节。",
    "auditPage.backHome": "返回首页",
    "auditPage.fieldName": "姓名",
    "auditPage.fieldCompany": "公司",
    "auditPage.companyPlaceholder": "公司名称",
    "auditPage.fieldWebsite": "网站 URL",
    "auditPage.challengesLabel": "有什么需要帮助的?(选填)",
    "auditPage.challengesPlaceholder": "例如:希望提升自然流量、降低广告成本...",
    "auditPage.errorMsg": "发生错误,请重试或给我们发邮件。",
    "auditPage.privacyNote": "我们严格保密您的数据。详情见",
    "auditPage.privacyLink": "隐私政策",
    // WeChat modal
    "wechat.scanFriend": "扫描二维码加我为好友",
  },
};

// ─── Path prefix helpers ─────────────────────────────────────────────────────
/**
 * Reads the language prefix from a pathname.
 *   "/en/rolunk" → { lang: "en", rest: "/rolunk" }
 *   "/zh"        → { lang: "zh", rest: "/" }
 *   "/rolunk"    → { lang: "hu", rest: "/rolunk" } (HU = default, no prefix)
 *   "/admin/..." → { lang: "hu", rest: "/admin/..." } (admin never prefixed)
 */
export function parseLangPath(path: string): { lang: Language; rest: string } {
  if (path.startsWith("/admin")) return { lang: "hu", rest: path };
  if (path === "/en" || path.startsWith("/en/")) {
    return { lang: "en", rest: path === "/en" ? "/" : path.slice(3) };
  }
  if (path === "/zh" || path.startsWith("/zh/")) {
    return { lang: "zh", rest: path === "/zh" ? "/" : path.slice(3) };
  }
  return { lang: "hu", rest: path };
}

export function buildLangPath(lang: Language, path: string): string {
  const clean = path.startsWith("/") ? path : `/${path}`;
  if (lang === "hu") return clean;
  return clean === "/" ? `/${lang}` : `/${lang}${clean}`;
}

export function langBase(lang: Language): string {
  return lang === "hu" ? "" : `/${lang}`;
}

// ─── Provider ────────────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const isValid = (v: unknown): v is Language => v === "hu" || v === "en" || v === "zh";
    // 1. URL path prefix (/en/... or /zh/...) — highest priority, owns the URL
    try {
      const { lang: pathLang } = parseLangPath(window.location.pathname);
      if (isValid(pathLang)) {
        // Only return non-HU directly from path; for HU, fall through to other signals
        // so that a user with saved preference "en" visiting "/" gets auto-redirected.
        if (pathLang !== "hu") return pathLang;
      }
    } catch {}
    // 2. Legacy ?lang= query param (backwards compat with earlier links)
    try {
      const urlParams = new URLSearchParams(window.location.search);
      const urlLang = urlParams.get("lang");
      if (isValid(urlLang)) return urlLang;
    } catch {}
    // 3. localStorage
    try {
      const stored = localStorage.getItem("g2a-lang");
      if (isValid(stored)) return stored;
    } catch {}
    // 4. Auto-detect from browser
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith("zh")) return "zh";
    if (browserLang.startsWith("hu")) return "hu";
    return "en";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    try { localStorage.setItem("g2a-lang", newLang); } catch {}
    document.documentElement.lang = newLang;
    // Rewrite URL to prefix form (full page nav keeps things simple & SEO-clean)
    try {
      const { rest } = parseLangPath(window.location.pathname);
      // Never touch admin URLs
      if (rest.startsWith("/admin")) return;
      const target = buildLangPath(newLang, rest) + window.location.search + window.location.hash;
      if (target !== window.location.pathname + window.location.search + window.location.hash) {
        window.location.href = target;
      }
    } catch {}
  };

  useEffect(() => {
    document.documentElement.lang = lang;
    // On first paint, migrate any legacy ?lang= URL to the new prefix form
    // and strip the now-redundant query param.
    try {
      const urlParams = new URLSearchParams(window.location.search);
      const queryLang = urlParams.get("lang");
      if (queryLang) {
        urlParams.delete("lang");
        const { rest } = parseLangPath(window.location.pathname);
        if (!rest.startsWith("/admin")) {
          const qs = urlParams.toString();
          const target = buildLangPath(lang, rest) + (qs ? `?${qs}` : "") + window.location.hash;
          if (target !== window.location.pathname + window.location.search + window.location.hash) {
            window.history.replaceState({}, "", target);
          }
        }
      }
    } catch {}
  }, [lang]);

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["hu"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
